/*
 * v1.11.3 - De Bello Gallico, Book VI top-up (2), taking it from 2 to 4 of its
 * allocated 6. Both chosen to sit against the two druid excerpts already there:
 * VI.16 is what the druids' schooling was for, VI.21 is the German contrast
 * Caesar builds the whole digression around.
 */
module.exports = [

{
  work: 'bg-vi', key: 'bg.6.16', prefix: '[16] ',
  citation: '(De Bello Gallico VI.16)',
  title: 'Figures of enormous size, their limbs woven from branches',
  titleIt: 'Simulacri di enorme grandezza, con le membra intrecciate di vimini',
  description: 'The passage that gave the modern world the wicker man. Read it next to the two druid chapters already here: those describe a training, and this describes what the training was for. Caesar reports it without a single word of comment.',
  descriptionIt: 'Il passo che ha dato al mondo moderno l\'uomo di vimini. Va letto accanto ai due capitoli sui druidi già presenti: quelli descrivono un addestramento, questo descrive a che cosa servisse. Cesare lo riferisce senza una sola parola di commento.',
  english: '> [16] **1.** The whole nation of the Gauls is exceedingly given to religious observances, **2.** and for that reason those who are afflicted with rather serious illnesses, and those who are engaged in battles and dangers, either sacrifice human beings as victims or vow that they will do so, and they employ the druids as the ministers of those sacrifices; **3.** because they judge that the will of the immortal gods cannot be appeased unless a human life is given back for a human life, and they have sacrifices of the same kind established as a public institution. Others have figures of enormous size, **4.** whose limbs, woven from branches, they fill with living men; and when these have been set alight, the men are enveloped by the flame and die. **5.** They judge that the execution of those caught in theft or robbery or some other offence is more pleasing to the immortal gods; but when the supply of that kind runs short, they come down even to the execution of the innocent.',
  italian: '> [16] **1.** L\'intera nazione dei Galli è oltremodo dedita alle pratiche religiose, **2.** e per questa ragione coloro che sono colpiti da malattie piuttosto gravi, e coloro che si trovano impegnati in battaglie e pericoli, o immolano uomini come vittime o fanno voto di immolarne, e si servono dei druidi come ministri di quei sacrifici; **3.** ritengono infatti che la volontà degli dèi immortali non possa essere placata se non si rende una vita umana in cambio di una vita umana, e hanno sacrifici dello stesso genere stabiliti come istituzione pubblica. Altri hanno simulacri di enorme grandezza, **4.** le cui membra, intrecciate di vimini, riempiono di uomini vivi; e appiccatovi il fuoco, gli uomini vengono avvolti dalla fiamma e muoiono. **5.** Ritengono che il supplizio di quanti sono stati sorpresi in furti o in rapine o in qualche altro reato sia più gradito agli dèi immortali; ma quando la disponibilità di quel genere viene meno, scendono perfino al supplizio degli innocenti.',
  analysis: 'The paragraph is built the way all Caesar\'s ethnography is built: the generalisation first, the evidence afterwards. *Natio est omnis Gallorum admodum dedita religionibus* states the conclusion in eight words, and everything that follows is offered as proof of it.\n\nWatch how carefully Caesar keeps himself out of the theology. *Arbitrantur*, *habent*, *putant*, *vovent* - they think, they have, they consider, they vow. He never says that a life must be given for a life; he says the Gauls judge that it cannot be otherwise. The logic of substitution is set out as their reasoning, in their voice, in one exact clause: *pro vita hominis nisi hominis vita reddatur*. It is theology reported as data.\n\nThe wicker colossus gets one sentence and no adjective of horror. *Quibus succensis circumventi flamma exanimantur homines*: when these have been set alight the men are killed, wrapped in the fire. Caesar adds nothing. The absence is doing the work, exactly as it does with the Helvetian census figures at *De Bello Gallico* I.29 - and a Roman audience, whose own state had buried people alive in the Forum Boarium within living memory, would have been quite capable of supplying the reaction themselves.\n\nThe last sentence is the one that lasts. Criminals are preferred, but when criminals run out *etiam ad innocentium supplicia descendunt*. *Descendere* is the verb for stooping to something beneath you, and it is the only word in the paragraph that carries a judgement.\n\nA caution worth carrying: this is testimony, not a photograph. Roman writers had a standing interest in barbarian human sacrifice, it was the traditional justification for suppressing druidism, and the archaeological record of Gallic ritual killing is far thinner than this paragraph suggests. What is certain is that Caesar wrote it, that Rome banned the druids within a century, and that the wicker figure has been in the European imagination ever since.',
  analysisIt: 'Il paragrafo è costruito come tutta l\'etnografia di Cesare: prima la generalizzazione, poi le prove. *Natio est omnis Gallorum admodum dedita religionibus* enuncia la conclusione in otto parole, e tutto ciò che segue è offerto come sua dimostrazione.\n\nSi osservi con quanta cura Cesare si tenga fuori dalla teologia. *Arbitrantur*, *habent*, *putant*, *vovent*: ritengono, hanno, credono, fanno voto. Non dice mai che una vita vada resa per una vita; dice che i Galli ritengono che non possa essere altrimenti. La logica della sostituzione è esposta come loro ragionamento, con la loro voce, in una proposizione esatta: *pro vita hominis nisi hominis vita reddatur*. È teologia riferita come dato.\n\nIl colosso di vimini riceve una frase sola e nemmeno un aggettivo di orrore. *Quibus succensis circumventi flamma exanimantur homines*: appiccatovi il fuoco, gli uomini muoiono avvolti dalla fiamma. Cesare non aggiunge nulla. È l\'assenza a fare il lavoro, esattamente come con le cifre del censimento elvetico in *De Bello Gallico* I.29 - e un pubblico romano, il cui Stato aveva sepolto vive delle persone nel Foro Boario a memoria d\'uomo, era perfettamente in grado di fornire da sé la reazione.\n\nL\'ultima frase è quella che resta. Si preferiscono i criminali, ma quando i criminali finiscono *etiam ad innocentium supplicia descendunt*. *Descendere* è il verbo che indica l\'abbassarsi a qualcosa di indegno, ed è l\'unica parola del paragrafo che porti un giudizio.\n\nUna cautela da tenere presente: questa è una testimonianza, non una fotografia. Gli scrittori romani avevano un interesse costante per il sacrificio umano barbarico, era la giustificazione tradizionale per reprimere il druidismo, e la documentazione archeologica dell\'uccisione rituale in Gallia è assai più esile di quanto questo paragrafo suggerisca. Certo è che Cesare lo scrisse, che Roma proibì i druidi entro un secolo, e che la figura di vimini è rimasta nell\'immaginario europeo da allora.'
},

{
  work: 'bg-vi', key: 'bg.6.21', prefix: '[21] ',
  citation: '(De Bello Gallico VI.21)',
  title: 'No druids, no sacrifices, and gods you can see',
  titleIt: 'Niente druidi, niente sacrifici, e dèi che si possono vedere',
  description: '*Germani multum ab hac consuetudine differunt.* Caesar puts the German digression immediately after the Gallic one, and defines the Germans entirely by what they lack. The contrast is not idle: it is the political argument of the whole war, in miniature.',
  descriptionIt: '*Germani multum ab hac consuetudine differunt.* Cesare colloca la digressione germanica subito dopo quella gallica, e definisce i Germani interamente per ciò che non hanno. Il contrasto non è ozioso: è l\'argomento politico dell\'intera guerra, in miniatura.',
  english: '> [21] **1.** The Germans differ greatly from this way of life. For they have no druids to preside over religious matters, nor are they much concerned with sacrifices. **2.** They count as gods only those whom they see and by whose resources they are plainly helped, the Sun and Vulcan and the Moon; of the rest they have not even heard by report. **3.** Their whole life consists of hunting and of the pursuits of war: from childhood they apply themselves to hard work and hardship. **4.** Those who have remained chaste the longest win the greatest praise among their own people: some think that this makes a man grow taller, others that it strengthens his sinews and his powers. **5.** To have had knowledge of a woman before the twentieth year they count among the most disgraceful things; and there is no concealing it, since they bathe together in the rivers and wear hides or small coverings of reindeer skin, with a great part of the body bare.',
  italian: '> [21] **1.** I Germani differiscono molto da questo modo di vivere. Non hanno infatti druidi che presiedano alle cose divine, né si curano granché dei sacrifici. **2.** Contano come dèi soltanto quelli che vedono e dalle cui risorse sono manifestamente aiutati: il Sole, Vulcano e la Luna; degli altri non hanno sentito parlare nemmeno per fama. **3.** Tutta la loro vita consiste nella caccia e nelle attività militari: fin da piccoli si dedicano alla fatica e alla durezza. **4.** Quelli che sono rimasti casti più a lungo ottengono la lode più grande fra i loro: alcuni pensano che questo faccia crescere di statura, altri che rafforzi i nervi e le forze. **5.** Aver conosciuto una donna prima del ventesimo anno lo considerano fra le cose più vergognose; e non c\'è modo di nasconderlo, perché si lavano tutti insieme nei fiumi e portano pelli o piccole coperture di renna, con gran parte del corpo nuda.',
  analysis: 'The first sentence is the architecture of the whole chapter: *Germani multum ab hac consuetudine differunt*. Everything after it is defined negatively, against the Gauls the reader has just been shown. No druids. No interest in sacrifice. No gods they cannot see. It is an ethnography written as a subtraction.\n\nSection 2 is the philosophically interesting one, and it needs a warning label. *Deorum numero eos solos ducunt, quos cernunt et quorum aperte opibus iuvantur* - a religion of visible, useful powers only. Then Caesar names them: *Solem et Vulcanum et Lunam*. Those are Roman names. The Germans did not call anyone Vulcan, and we have no idea what they did call the god of fire, if they had one. This is *interpretatio Romana*, the automatic habit of translating a foreign pantheon into your own, and it is the single largest reason this chapter has to be handled carefully as evidence.\n\nThe rest is an austerity programme: hunting and war, hardship from infancy, chastity rewarded with prestige and believed to make you taller, near-nakedness in animal skins. Every item contrasts with something Roman as much as with something Gallic.\n\nAnd that is the point. Go back to the first sentence of the whole work - *De Bello Gallico* I.1, where the Belgae are bravest because they are furthest from traders and *ea quae ad effeminandos animos pertinent*, the things that soften the spirit. This chapter is that theory\'s other end. Germans are hard because they have nothing; Gauls are softer because they have wine and roads and towns; and a Gaul standing between the Roman Province and the Rhine is therefore a man who needs protecting - which happens to require a Roman army in Gaul indefinitely. Book VI\'s great ethnographic digression, the most disinterested-looking writing in the corpus, is doing exactly the same work as the first sentence of Book I.',
  analysisIt: 'La prima frase è l\'architettura dell\'intero capitolo: *Germani multum ab hac consuetudine differunt*. Tutto ciò che segue è definito per via negativa, contro i Galli che il lettore ha appena visto. Niente druidi. Nessun interesse per i sacrifici. Nessun dio che non si possa vedere. È un\'etnografia scritta come sottrazione.\n\nIl paragrafo 2 è quello filosoficamente interessante, e ha bisogno di un\'avvertenza. *Deorum numero eos solos ducunt, quos cernunt et quorum aperte opibus iuvantur*: una religione di potenze soltanto visibili e utili. Poi Cesare li nomina: *Solem et Vulcanum et Lunam*. Sono nomi romani. I Germani non chiamavano nessuno Vulcano, e non abbiamo idea di come chiamassero il dio del fuoco, ammesso che ne avessero uno. È l\'*interpretatio Romana*, l\'abitudine automatica di tradurre un pantheon straniero nel proprio, ed è la ragione principale per cui questo capitolo va maneggiato con prudenza come documento.\n\nIl resto è un programma di austerità: caccia e guerra, durezza fin dall\'infanzia, castità premiata con il prestigio e ritenuta capace di far crescere di statura, seminudità nelle pelli. Ogni voce contrasta con qualcosa di romano tanto quanto con qualcosa di gallico.\n\nEd è questo il punto. Si torni alla prima frase dell\'opera, *De Bello Gallico* I.1, dove i Belgi sono i più valorosi perché sono i più lontani dai mercanti e da *ea quae ad effeminandos animos pertinent*, le cose che infiacchiscono gli animi. Questo capitolo è l\'altro capo di quella teoria. I Germani sono duri perché non hanno nulla; i Galli sono più molli perché hanno vino, strade e città; e un Gallo che sta fra la Provincia romana e il Reno è dunque un uomo che va protetto, il che richiede per l\'appunto un esercito romano in Gallia a tempo indeterminato. La grande digressione etnografica del libro VI, la scrittura dall\'aria più disinteressata di tutto il corpus, svolge esattamente lo stesso lavoro della prima frase del libro I.'
}

];
