/*
 * v1.13.1 - De Bello Gallico VIII, part 2 of 2: the spring, the settlement,
 * the canvass, and the two legions. Latin from batch/passages1131.json,
 * extracted verbatim. Section markers follow Perseus exactly - note that
 * 50.3 stops on a comma and 50.4 resumes with `simulque`, so all three texts
 * break in the middle of that sentence.
 */
module.exports = [

{
  work: 'bellum-gallicum-viii', key: 'bg.8.43', prefix: '[43] ',
  citation: '(De Bello Gallico VIII.43)',
  title: 'The spring dried up',
  titleIt: 'La sorgente si seccò',
  description: 'The tunnels reach the veins of the spring. The water fails in a single day, the defenders can see no cause for it, and the last town in Gaul surrenders to what it takes for the will of the gods.',
  descriptionIt: 'I cunicoli raggiungono le vene della sorgente. L\'acqua viene meno in un giorno solo, i difensori non ne vedono la causa, e l\'ultima città della Gallia si arrende a quella che prende per volontà degli dèi.',
  english: '> [43] **1.** When Caesar saw that a good many of his men were being wounded, he orders cohorts to climb the hill from every side of the town and, pretending they mean to seize the walls, to raise a shout everywhere. **2.** At this the townspeople took fright, and since they were in suspense about what was happening in the other quarters, they call back the armed men from attacking the works and post them along the walls. **3.** So our men, the battle over, quickly put out part of the works that the flames had caught and cut away the rest. **4.** The townspeople resisted stubbornly, and even after losing a great part of their people to thirst they stayed by their decision; at last the veins of the spring were cut through by tunnels and turned aside. **5.** At this the ever-flowing spring suddenly dried up, and it brought the townspeople such despair of survival that they thought it had been done not by the plan of men but by the will of the gods. And so, forced by necessity, they surrendered.',
  italian: '> [43] **1.** Vedendo Cesare che parecchi dei suoi venivano feriti, ordina che da ogni lato della città delle coorti salgano il monte e, fingendo di voler occupare le mura, levino ovunque un clamore. **2.** A questo i cittadini si spaventarono e, poiché erano in ansia per quello che accadeva negli altri punti, richiamano gli armati dall\'assalto alle opere e li dispongono lungo le mura. **3.** Così i nostri, finito lo scontro, spengono rapidamente una parte delle opere che le fiamme avevano preso e tagliano via il resto. **4.** I cittadini resistevano con ostinazione e, pur avendo perduto per la sete gran parte dei loro, restavano nella loro decisione; alla fine le vene della sorgente furono tagliate con dei cunicoli e deviate. **5.** A questo la sorgente perenne si seccò all\'improvviso e portò ai cittadini una tale disperazione di salvezza che pensarono fosse accaduto non per disegno di uomini, ma per volontà degli dèi. E così, costretti dalla necessità, si arresero.',
  analysis: '**Where we are.** Uxellodunum, in the country of the Cadurci, late summer 51 BC - the last town in Gaul still holding out, eight years after Caesar crossed the Rhone. `VIII.41` built the ramp and the ten-storey tower to keep the defenders off the one spring below the walls, `VIII.42` was their attempt to burn the whole thing, and this chapter is the end of the siege and of the Gallic War as a military operation.\n\n**The first move is a feint, and it is described with the mechanism showing.** Caesar sends cohorts up the hill *simulatione moenium occupandorum* - with a pretence of seizing the walls - and has them shout from every side. It works because of a specific fact about defending a hill town: *cum quid ageretur in locis reliquis essent suspensi*, **they could not see what was happening in the other quarters.** A defender is always short of information, and the shout is aimed at the gap.\n\n**Then the sentence the siege was built for.** *Ad postremum cuniculis venae fontis intercisae sunt atque aversae. Quo facto repente perennis exaruit fons* - the veins of the spring were cut and diverted by mines, **and the ever-flowing spring suddenly dried up.** Note *perennis*: the word means a spring that has never failed, which is exactly why a town was built above it, and exactly why the townspeople cannot read what has happened.\n\n**And that is the point of the chapter.** They could see the ramp and the tower - those were built in daylight to be seen. **They could not see the mines**, and the mines are what did it. So the evidence available to them is: a spring that has run for ever stops in a day, for no visible cause. The conclusion they draw is the only rational one from that evidence: *non hominum consilio, sed deorum voluntate factum*, not by the plan of men but by the will of the gods. **The tower was a very expensive way of making the mines invisible.**\n\n**Hirtius does not comment**, and the restraint is worth noticing, because the sentence is set up to be commented on - a Roman writer had every licence to say something here about barbarian superstition. What he writes instead is *se necessitate coacti tradiderunt*: they surrendered under compulsion. **A town that has watched its people die of thirst is not being superstitious.** The next chapter, `VIII.44`, is what Caesar did to the survivors.',
  analysisIt: '**Dove siamo.** Uxellodunum, nel paese dei Cadurci, fine estate del 51 a.C.: l\'ultima città della Gallia che ancora resiste, otto anni dopo che Cesare ha passato il Rodano. `VIII.41` ha costruito il terrapieno e la torre di dieci piani per tenere i difensori lontani dall\'unica sorgente sotto le mura, `VIII.42` è stato il loro tentativo di bruciare tutto, e questo capitolo è la fine dell\'assedio e della guerra gallica come operazione militare.\n\n**La prima mossa è una finta, ed è descritta con il meccanismo in vista.** Cesare manda delle coorti su per il monte *simulatione moenium occupandorum*, fingendo di occupare le mura, e le fa gridare da ogni lato. Funziona per un fatto preciso della difesa di una città d\'altura: *cum quid ageretur in locis reliquis essent suspensi*, **non potevano vedere che cosa accadesse negli altri punti.** Un difensore è sempre a corto di informazioni, e il clamore punta proprio a quel vuoto.\n\n**Poi la frase per cui l\'assedio era stato costruito.** *Ad postremum cuniculis venae fontis intercisae sunt atque aversae. Quo facto repente perennis exaruit fons*: le vene della sorgente furono tagliate e deviate con i cunicoli, **e la sorgente perenne si seccò all\'improvviso.** Si noti *perennis*: la parola indica una sorgente che non è mai venuta meno, che è esattamente il motivo per cui sopra vi si era costruita una città, ed esattamente il motivo per cui i cittadini non riescono a leggere quello che è successo.\n\n**Ed è questo il punto del capitolo.** Il terrapieno e la torre li vedevano: erano stati costruiti alla luce del sole per essere visti. **I cunicoli non li vedevano**, e sono i cunicoli ad aver fatto tutto. Le prove a loro disposizione sono dunque: una sorgente che scorre da sempre si ferma in un giorno, senza causa visibile. La conclusione che ne traggono è l\'unica razionale a partire da quelle prove: *non hominum consilio, sed deorum voluntate factum*, non per disegno di uomini ma per volontà degli dèi. **La torre è stata un modo molto costoso di rendere invisibili le mine.**\n\n**Irzio non commenta**, e la sobrietà merita attenzione, perché la frase è predisposta per un commento: uno scrittore romano aveva ogni licenza di dire qualcosa qui sulla superstizione dei barbari. Quello che scrive invece è *se necessitate coacti tradiderunt*, si arresero costretti dalla necessità. **Una città che ha visto morire di sete i suoi non sta facendo della superstizione.** Il capitolo seguente, `VIII.44`, è quello che Cesare fece ai superstiti.'
},

{
  work: 'bellum-gallicum-viii', key: 'bg.8.49', prefix: '[49] ',
  citation: '(De Bello Gallico VIII.49)',
  title: 'Nothing to leave behind',
  titleIt: 'Non lasciare niente dietro di sé',
  description: 'The winter after the fighting stops, and the whole occupation policy in one sentence: keep the states friendly and give nobody a reason to take up arms - because a war left behind at the handover would be a war Caesar could not leave.',
  descriptionIt: 'L\'inverno dopo la fine dei combattimenti, e tutta la politica di occupazione in una frase: tenere buone le nazioni e non dare a nessuno un motivo per prendere le armi, perché una guerra lasciata al momento del passaggio di consegne sarebbe una guerra da cui Cesare non potrebbe andarsene.',
  english: '> [49] **1.** While Caesar was wintering in Belgic country he had that one purpose: to keep the states in friendship, to give nobody either hope or grounds for arms. **2.** For there was nothing he wanted less than to have some necessity of waging war imposed on him just as he was leaving, so that when he had to withdraw the army some war should be left behind which the whole of Gaul would gladly take up with no danger present. **3.** And so, by addressing the states with honour, by loading the leading men with the greatest rewards, by imposing no burdens, he easily kept in peace a Gaul worn out by so many defeats, the terms of obedience now being better.',
  italian: '> [49] **1.** Mentre Cesare svernava nel paese dei Belgi, aveva quell\'unico proposito: tenere le nazioni nell\'amicizia, non dare a nessuno né speranza né motivo di prendere le armi. **2.** Nulla infatti voleva meno che vedersi imposta, proprio mentre stava per andarsene, la necessità di condurre una guerra, così che, dovendo ritirare l\'esercito, restasse dietro di sé una guerra che tutta la Gallia avrebbe intrapreso volentieri, non essendoci più un pericolo immediato. **3.** E così, rivolgendosi alle nazioni con onore, colmando i maggiorenti delle più grandi ricompense, non imponendo alcun onere, tenne facilmente in pace una Gallia sfinita da tante sconfitte, essendo ormai migliori le condizioni dell\'obbedienza.',
  analysis: '**Where we are.** The winter of 51-50 BC, in the country of the Belgae. The fighting is over: Uxellodunum has fallen (`VIII.43`), Ambiorix has vanished, and Caesar\'s command in Gaul is running out. **The whole chapter is about the handover** - the moment when he must take the army out and hand the province to a successor - and about what a departing governor is afraid of.\n\n**Section 2 states the fear precisely**, and it is worth taking apart. *Ne, cum exercitum deducturus esset, bellum aliquod relinqueretur quod omnis Gallia libenter sine praesenti periculo susciperet.* The danger is not a war now; it is a war **left behind**, one that all Gaul would take up gladly *sine praesenti periculo* - with no danger present, which is to say once the legions have gone. **A conquest is not finished when resistance stops; it is finished when it can survive the conqueror leaving.**\n\n**And section 3 is the policy, in three gerunds.** *Honorifice civitates appellando, principes maximis praemiis adficiendo, nulla onera iniungendo*: addressing the states with honour, rewarding the leading men enormously, imposing no burdens. **No garrisons, no taxes, no punishments in the list at all** - the instruments are courtesy, money for the aristocracy, and the deliberate absence of demands. This is the same Caesar who two chapters earlier cut the hands off a garrison (`VIII.44`), and both are policy: terror for a town that broke faith, purchase for a nobility that might keep it.\n\n**The last phrase carries the whole thing.** *Condicione parendi meliore* - **the terms of obeying being better.** Not freedom, not alliance: obedience, on improved terms. Hirtius has written the sentence from inside the Roman view and has not softened the noun, and *defessam tot adversis proeliis Galliam*, a Gaul worn out by so many lost battles, tells you what the other half of the arrangement was.\n\n**And it held.** When the civil war began fourteen months later Caesar took most of his army out of Gaul, and Gaul did not rise. **The only real test of this chapter\'s policy was passed in his absence**, which is more than can be said for most of what the eight books describe.',
  analysisIt: '**Dove siamo.** L\'inverno del 51-50 a.C., nel paese dei Belgi. I combattimenti sono finiti: Uxellodunum è caduta (`VIII.43`), Ambiorige è scomparso, e il comando di Cesare in Gallia sta per scadere. **Tutto il capitolo riguarda il passaggio di consegne** - il momento in cui dovrà portar via l\'esercito e consegnare la provincia a un successore - e ciò di cui un governatore in partenza ha paura.\n\n**Il paragrafo 2 enuncia la paura con precisione**, e vale la pena smontarlo. *Ne, cum exercitum deducturus esset, bellum aliquod relinqueretur quod omnis Gallia libenter sine praesenti periculo susciperet.* Il pericolo non è una guerra adesso; è una guerra **lasciata dietro**, che tutta la Gallia intraprenderebbe volentieri *sine praesenti periculo*, non essendoci un pericolo immediato, cioè una volta partite le legioni. **Una conquista non è finita quando cessa la resistenza; è finita quando sopravvive alla partenza del conquistatore.**\n\n**E il paragrafo 3 è la politica, in tre gerundi.** *Honorifice civitates appellando, principes maximis praemiis adficiendo, nulla onera iniungendo*: rivolgersi alle nazioni con onore, ricompensare enormemente i maggiorenti, non imporre alcun onere. **Nell\'elenco non ci sono presidi, né tributi, né punizioni**: gli strumenti sono la cortesia, il denaro per l\'aristocrazia e l\'assenza deliberata di richieste. È lo stesso Cesare che due capitoli prima ha fatto tagliare le mani a un presidio (`VIII.44`), e sono entrambe politica: terrore per una città che ha rotto la parola, acquisto per una nobiltà che potrebbe mantenerla.\n\n**L\'ultima espressione regge tutto.** *Condicione parendi meliore*, **essendo migliori le condizioni dell\'obbedire.** Non libertà, non alleanza: obbedienza, a condizioni migliorate. Irzio ha scritto la frase da dentro il punto di vista romano e non ha addolcito il sostantivo, e *defessam tot adversis proeliis Galliam*, una Gallia sfinita da tante battaglie perdute, dice qual era l\'altra metà dell\'accordo.\n\n**E tenne.** Quando la guerra civile cominciò, quattordici mesi dopo, Cesare portò fuori dalla Gallia quasi tutto l\'esercito, e la Gallia non insorse. **L\'unica vera prova della politica di questo capitolo fu superata in sua assenza**, il che è più di quanto si possa dire di gran parte di ciò che gli otto libri raccontano.'
},

{
  work: 'bellum-gallicum-viii', key: 'bg.8.50', prefix: '[50] ',
  citation: '(De Bello Gallico VIII.50)',
  title: 'Canvassing for Antony',
  titleIt: 'La campagna elettorale per Antonio',
  description: 'Caesar leaves winter quarters early and goes down through Italy town by town, thanking people for a vote that has already been won - and the excuse he gives himself contains the exact phrase the Civil War will open with.',
  descriptionIt: 'Cesare lascia i quartieri d\'inverno in anticipo e scende per l\'Italia città per città, a ringraziare per un voto già vinto; e la scusa che dà a se stesso contiene esattamente l\'espressione con cui si aprirà la guerra civile.',
  english: '> [50] **1.** He himself, once the winter quarters were finished with, set out for Italy against his custom by the longest possible marches, to canvass the towns and colonies to which he had recommended the candidacy for a priesthood of Mark Antony, his quaestor. **2.** For he was exerting his influence both gladly on behalf of a man very closely bound to him, whom he had sent ahead a little earlier to stand, and keenly against the faction and the power of a few men, who by the defeat of Mark Antony wanted to break down the influence of Caesar as he left his province. **3.** Although he had heard on the road, before reaching Italy, that Antony had already been made an augur, he thought he had a no less good reason for visiting the towns and colonies: to thank them for having turned out in numbers and done their duty by Antony, **4.** and at the same time to commend himself and his own candidacy for the following year - because his opponents were boasting insolently that Lucius Lentulus and Gaius Marcellus had been elected consuls to strip Caesar of every office and every mark of standing, and that the consulship had been snatched from Servius Galba, though he had been far stronger in influence and in votes, because he was bound to Caesar by friendship and by having served with him as legate.',
  italian: '> [50] **1.** Lui stesso, terminati i quartieri d\'inverno, partì per l\'Italia contro la sua abitudine a marce quanto più rapide possibile, per fare campagna presso i municipi e le colonie a cui aveva raccomandato la candidatura a un sacerdozio di Marco Antonio, suo questore. **2.** Metteva infatti in gioco il proprio credito sia volentieri a favore di un uomo legatissimo a lui, che poco prima aveva mandato avanti a candidarsi, sia con accanimento contro la fazione e il potere di pochi, i quali con la sconfitta di Marco Antonio volevano abbattere il credito di Cesare che lasciava la provincia. **3.** Benché avesse saputo per strada, prima di raggiungere l\'Italia, che Antonio era già stato fatto augure, ritenne di avere una ragione non meno valida per visitare i municipi e le colonie: ringraziarli per essersi presentati in massa e aver fatto il loro dovere verso Antonio, **4.** e insieme raccomandare se stesso e la propria candidatura dell\'anno seguente, perché i suoi avversari si vantavano con arroganza che Lucio Lentulo e Gaio Marcello erano stati eletti consoli per spogliare Cesare di ogni carica e di ogni segno di prestigio, e che il consolato era stato strappato a Servio Galba, benché fosse stato molto più forte per credito e per voti, perché era legato a Cesare dall\'amicizia e dall\'aver servito con lui come legato.',
  analysis: '**Where we are.** The spring of 50 BC. Gaul is quiet, Caesar\'s command has about a year to run, and this chapter is the moment the book stops being about a war. **Mark Antony** is his quaestor, standing for a place in the college of augurs; **Lucius Lentulus and Gaius Marcellus** are the consuls elected for 49, both hostile; **Servius Galba** is a former legate of Caesar\'s (the one who held the Alpine pass in *De Bello Gallico* III.1) who lost the consular election. An **augurate** is not a religious hobby: it is a life office, held by senators, that carries the right to declare the auspices unfavourable and stop public business. It is a political asset, and everyone treats it as one.\n\n**The first two words of the chapter are the argument.** *Contra consuetudinem* - **against his custom.** Caesar habitually stays with the army; this year he leaves early and marches *quam maximis itineribus*, at the fastest possible rate, to canvass Italian towns. The forced marches that took him to Alesia are being spent on an election.\n\n**Then section 3 gives away the game with perfect composure.** He learns on the road that Antony has already won. He goes anyway - *non minus iustam sibi causam... existimavit*, he judged he had a no less good reason - and the reason is to *thank* the towns for turning out. **You do not need to canvass a completed election; you do need to be seen in the towns whose votes you will want next year**, and section 4 says so outright: *simulque se et honorem suum sequentis anni commendaret*.\n\n**And here is the phrase to remember.** *Contra factionem et potentiam paucorum* - against the faction and the power of a few. **That is the thesis of the entire *Bellum Civile***: at *De Bello Civili* I.22 Caesar says he left his province to free himself and the Roman people *a factione paucorum*, and at I.9 the same handful of enemies is the whole account of the war. Hirtius has planted the slogan **nine months before the Rubicon**, in a chapter about canvassing.\n\n**And the style is unmistakably not Caesar\'s.** Caesar reports Roman politics rarely and flatly. Hirtius here reports what the other side was *boasting* - *insolenter adversarii sui gloriarentur* - and lets a sentence run through an election result, a stripped honour, a lost consulship and a friendship, all subordinated to somebody else\'s bragging. **Caesar gives you his own reasoning; Hirtius gives you the gossip of the year**, and for 50 BC the gossip is the history.',
  analysisIt: '**Dove siamo.** Primavera del 50 a.C. La Gallia è tranquilla, al comando di Cesare resta circa un anno, e questo capitolo è il momento in cui il libro smette di parlare di una guerra. **Marco Antonio** è il suo questore e si candida a un posto nel collegio degli auguri; **Lucio Lentulo e Gaio Marcello** sono i consoli eletti per il 49, entrambi ostili; **Servio Galba** è un ex legato di Cesare (quello che tenne il passo alpino nel *De Bello Gallico* III.1) che ha perso l\'elezione consolare. Un **augurato** non è un passatempo religioso: è una carica a vita, tenuta da senatori, che dà il diritto di dichiarare sfavorevoli gli auspici e bloccare gli affari pubblici. È un bene politico, e tutti lo trattano come tale.\n\n**Le prime due parole del capitolo sono l\'argomento.** *Contra consuetudinem*, **contro la sua abitudine.** Cesare di norma resta con l\'esercito; quest\'anno parte in anticipo e marcia *quam maximis itineribus*, alla massima velocità possibile, per fare campagna nei municipi italici. Le marce forzate che lo portarono ad Alesia vengono spese per un\'elezione.\n\n**Poi il paragrafo 3 scopre le carte con perfetta compostezza.** Per strada apprende che Antonio ha già vinto. Va lo stesso - *non minus iustam sibi causam... existimavit*, ritenne di avere una ragione non meno valida - e la ragione è *ringraziare* i municipi per essersi presentati. **Non serve fare campagna per un\'elezione già conclusa; serve invece farsi vedere nelle città di cui vorrai i voti l\'anno prossimo**, e il paragrafo 4 lo dice apertamente: *simulque se et honorem suum sequentis anni commendaret*.\n\n**Ed ecco l\'espressione da ricordare.** *Contra factionem et potentiam paucorum*, contro la fazione e il potere di pochi. **È la tesi di tutto il *Bellum Civile***: nel *De Bello Civili* I.22 Cesare dice di aver lasciato la provincia per liberare sé e il popolo romano *a factione paucorum*, e in I.9 quella stessa manciata di nemici è l\'intera spiegazione della guerra. Irzio ha piantato lo slogan **nove mesi prima del Rubicone**, in un capitolo di campagna elettorale.\n\n**E lo stile non è affatto quello di Cesare.** Cesare riferisce la politica romana di rado e in modo piatto. Irzio qui riferisce di che cosa si *vantasse* l\'altra parte - *insolenter adversarii sui gloriarentur* - e lascia correre una frase attraverso un risultato elettorale, un onore sottratto, un consolato perduto e un\'amicizia, tutto subordinato alle spacconate di qualcun altro. **Cesare vi dà il proprio ragionamento; Irzio vi dà le chiacchiere dell\'anno**, e per il 50 a.C. le chiacchiere sono la storia.'
},

{
  work: 'bellum-gallicum-viii', key: 'bg.8.54', prefix: '[54] ',
  citation: '(De Bello Gallico VIII.54)',
  title: 'Two legions taken from one man',
  titleIt: 'Due legioni tolte a uno solo',
  description: 'The senate votes one legion each from Pompey and Caesar for the Parthian war. Pompey supplies his by asking back the legion he had lent Caesar, so that both legions come out of the same army - and everyone can see it.',
  descriptionIt: 'Il senato vota una legione ciascuno da Pompeo e da Cesare per la guerra partica. Pompeo fornisce la sua richiedendo la legione che aveva prestato a Cesare, sicché entrambe le legioni escono dallo stesso esercito, e lo vedono tutti.',
  english: '> [54] **1.** Then a decree of the senate is passed, that for the Parthian war one legion should be sent by Gnaeus Pompey and another by Gaius Caesar; and it is not obscure that two legions are being taken from one man. **2.** For Gnaeus Pompey gave, as though out of his own number, the First legion, which he had sent to Caesar, raised by a levy in Caesar\'s province. **3.** Caesar nevertheless, although there was no doubt at all about the intention of his opponents, sent the legion back to Pompey and, in his own name, orders the Fifteenth, which he had had in Nearer Gaul, to be handed over in accordance with the decree of the senate. In its place he sends the Thirteenth legion to Italy to guard the garrison posts from which the Fifteenth was being withdrawn. **4.** He himself distributes the winter quarters to the army: he stations Gaius Trebonius with four legions in Belgic country, and takes Gaius Fabius with as many into the land of the Aedui. **5.** For he thought Gaul would be safest in this way, if the Belgae, whose courage was greatest, and the Aedui, whose authority was highest, were held down by armies. He himself set out for Italy.',
  italian: '> [54] **1.** Viene poi approvato un decreto del senato: che per la guerra partica una legione sia mandata da Gneo Pompeo e un\'altra da Gaio Cesare; e non è affatto oscuro che due legioni vengono tolte a uno solo. **2.** Gneo Pompeo infatti diede, come se fosse del proprio contingente, la Prima legione, che aveva mandato a Cesare e che era stata arruolata nella provincia di Cesare. **3.** Cesare tuttavia, benché non ci fosse alcun dubbio sull\'intenzione dei suoi avversari, rimandò a Pompeo la legione e a proprio nome ordina che sia consegnata, secondo il decreto del senato, la Quindicesima, che aveva tenuto nella Gallia Cisalpina. Al suo posto manda in Italia la Tredicesima legione a difendere i presidi da cui la Quindicesima veniva ritirata. **4.** Lui stesso distribuisce all\'esercito i quartieri d\'inverno: colloca Gaio Trebonio con quattro legioni nel paese dei Belgi, conduce Gaio Fabio con altrettante nel paese degli Edui. **5.** Riteneva infatti che la Gallia sarebbe stata sicurissima così, se i Belgi, il cui valore era il più grande, e gli Edui, la cui autorità era la più alta, fossero tenuti a freno da eserciti. Lui stesso partì per l\'Italia.',
  analysis: '**Where we are.** Late in 50 BC, the last full chapter of narrative in the *De Bello Gallico* before the closing note of `VIII.55`. Rome has just lost an army in the east - Crassus was destroyed at Carrhae in 53 - and a **Parthian war** is the official reason for what happens here. **The First legion** had been lent by Pompey to Caesar in 53, after the disaster of Sabinus and Cotta; the loan is about to be called in.\n\n**Section 1 says the quiet part out loud, and this is why the chapter is in the app.** *Neque obscure duae legiones uni detrahuntur* - **it is not obscure that two legions are being taken from one man.** A senatorial decree that looks perfectly balanced, one legion each, is not balanced at all; and Hirtius does not build to the revelation or withhold it for effect. He states the arithmetic in the same sentence as the decree. **Caesar would have narrated the decree and let you notice.**\n\n**Section 2 is the mechanism.** Pompey supplies his legion by taking back the First - a legion he had *lent* to Caesar, and which had been *raised in Caesar\'s province* in the first place - *tamquam ex suo numero*, **as though out of his own number.** Every man in it is a soldier Caesar levied. The manoeuvre is legally impeccable and materially a two-for-nothing.\n\n**And section 3 is Caesar\'s reply, which is the interesting decision.** He knows exactly what is being done - *cum de voluntate minime dubium esset adversariorum suorum*, there was no doubt at all about his opponents\' intention - **and he complies in full.** He returns the First, hands over the Fifteenth as well, and even backfills the garrisons the Fifteenth was holding by sending the Thirteenth into Italy. He gives up two veteran legions and takes the position that he has obeyed the senate to the letter. **The Thirteenth is the legion he will cross the Rubicon with**, five months later.\n\n**And then the last two sentences, which are ordinary and are not.** He billets eight legions on the Belgae and the Aedui, *quorum maxima virtus* and *quorum auctoritas summa* - the bravest people and the most influential one, each with an army sitting on it. **The occupation of Gaul is now four sentences of housekeeping.** And the book\'s last movement is three words: *Ipse in Italiam profectus est*. He set out for Italy. **Read what he is walking towards** - a hostile pair of consuls (`VIII.50`), an army two legions lighter, and a command running out - **and the flattest sentence in the book turns out to be the loudest.**',
  analysisIt: '**Dove siamo.** Fine del 50 a.C., l\'ultimo capitolo narrativo del *De Bello Gallico* prima della nota conclusiva di `VIII.55`. Roma ha appena perso un esercito in oriente - Crasso fu distrutto a Carre nel 53 - e una **guerra partica** è la ragione ufficiale di quanto accade qui. **La Prima legione** era stata prestata da Pompeo a Cesare nel 53, dopo il disastro di Sabino e Cotta; il prestito sta per essere richiamato.\n\n**Il paragrafo 1 dice ad alta voce quello che di solito si tace, ed è la ragione per cui il capitolo sta nell\'app.** *Neque obscure duae legiones uni detrahuntur*, **non è affatto oscuro che due legioni vengono tolte a uno solo.** Un decreto del senato che sembra perfettamente equilibrato, una legione a testa, non è affatto equilibrato; e Irzio non prepara la rivelazione né la trattiene per l\'effetto. Enuncia il conto nella stessa frase del decreto. **Cesare avrebbe raccontato il decreto e lasciato che ve ne accorgeste.**\n\n**Il paragrafo 2 è il meccanismo.** Pompeo fornisce la sua legione riprendendosi la Prima, una legione che aveva *prestato* a Cesare e che era stata *arruolata nella provincia di Cesare*, *tamquam ex suo numero*, **come se fosse del proprio contingente.** Ogni uomo che vi sta dentro è un soldato reclutato da Cesare. La manovra è giuridicamente impeccabile e materialmente un due a zero.\n\n**E il paragrafo 3 è la risposta di Cesare, che è la decisione interessante.** Sa benissimo che cosa gli stanno facendo - *cum de voluntate minime dubium esset adversariorum suorum*, non c\'era alcun dubbio sull\'intenzione dei suoi avversari - **e obbedisce per intero.** Restituisce la Prima, consegna anche la Quindicesima e per giunta rimpiazza i presidi che la Quindicesima teneva mandando la Tredicesima in Italia. Cede due legioni di veterani e assume la posizione di chi ha obbedito al senato alla lettera. **La Tredicesima è la legione con cui passerà il Rubicone**, cinque mesi dopo.\n\n**E poi le ultime due frasi, che sono ordinarie e non lo sono.** Acquartiera otto legioni sui Belgi e sugli Edui, *quorum maxima virtus* e *quorum auctoritas summa*, il popolo più valoroso e quello più influente, ciascuno con un esercito addosso. **L\'occupazione della Gallia è ormai quattro frasi di amministrazione.** E l\'ultimo movimento del libro sta in tre parole: *Ipse in Italiam profectus est*. Partì per l\'Italia. **Si guardi verso che cosa sta camminando** - una coppia di consoli ostili (`VIII.50`), un esercito più leggero di due legioni e un comando in scadenza - **e la frase più piatta del libro si rivela la più rumorosa.**'
}

];
