/*
 * v1.11.3 - De Bello Gallico, Book IV (5). The Germans, the Rhine bridge, the
 * first landing in Britain. Same rules as frags1113a.js.
 */
module.exports = [

{
  work: 'bg-iv', key: 'bg.4.5', prefix: '[5] ',
  citation: '(De Bello Gallico IV.5)',
  title: 'They stop travellers on the road and make them talk',
  titleIt: 'Fermano i viandanti sulla strada e li costringono a parlare',
  description: 'A short digression on the Gallic character, and one of the most quoted paragraphs in the book. It is also the best evidence we have for how news actually moved in Gaul, and, read a second time, a piece of political self-justification.',
  descriptionIt: 'Una breve digressione sul carattere gallico, e uno dei paragrafi più citati del libro. È anche la migliore testimonianza che abbiamo su come circolassero davvero le notizie in Gallia e, a una seconda lettura, un pezzo di autogiustificazione politica.',
  english: '> [5] **1.** Informed of these matters, and fearing the unsteadiness of the Gauls, because they are changeable in forming their decisions and generally set on novelty, Caesar thought that nothing should be entrusted to them. **2.** For this is a Gallic custom: that they compel travellers to stop, even against their will, and demand what each of them has heard or learned about any matter, and that in the towns the common people crowd round traders and force them to declare what regions they have come from and what they have learned there. **3.** Stirred up by these things and by hearsay, they often form plans about the highest matters, of which they must repent on the spot, since they are slaves to uncertain rumours and most people answer with inventions to suit them.',
  italian: '> [5] **1.** Informato di questi fatti, e temendo l\'incostanza dei Galli, poiché sono mutevoli nel prendere decisioni e in genere avidi di novità, Cesare ritenne che non si dovesse affidare loro nulla. **2.** È infatti costume gallico questo: che costringano i viandanti a fermarsi, anche contro la loro volontà, e chiedano a ciascuno che cosa abbia sentito o appreso su qualunque argomento, e che nelle città la gente comune circondi i mercanti e li obblighi a dichiarare da quali regioni provengano e che cosa vi abbiano saputo. **3.** Eccitati da queste cose e dalle chiacchiere, prendono spesso decisioni sulle questioni più gravi, delle quali devono pentirsi all\'istante, dal momento che sono schiavi di voci incerte e i più rispondono con invenzioni fatte apposta per compiacerli.',
  analysis: 'Take section 2 on its own and it is one of the most valuable paragraphs in the *Corpus Caesarianum*, because it is not about war at all. It is about information: no newspapers, no posts, no roads worth the name, and so a whole people gets its news by stopping strangers and squeezing them. The detail of the crowd closing around a merchant in a market square is precisely observed, and there is nothing else like it in Latin literature.\n\nNow read section 1 and section 3, which wrap it. *Infirmitas*, *mobiles*, *novis rebus student* - unsteadiness, changeability, an appetite for revolution - is the standard Roman vocabulary for political unreliability, and Caesar deploys all three before a single piece of evidence has been offered. The conclusion is stated before the observation: *nihil his committendum existimavit*, nothing should be entrusted to them.\n\nThat is the shape of the whole digression, and it is worth seeing plainly. An accurate ethnographic detail is set between a prejudice and a policy, and it lends both its credibility. If Gauls really do decide great questions from market gossip, then they cannot govern themselves, and someone has to do it for them. Every generalisation in this paragraph is doing political work.\n\nThe closing clause is also the most cynical sentence in Book IV, and the most modern: *pleri ad voluntatem eorum ficta respondeant* - most people make things up to suit what the crowd wants. Grammatically, watch *quorum eos in vestigio paenitere necesse est*: impersonal *paenitet* takes the person in the accusative and the thing regretted in the genitive, so it is "they must repent of which on the spot", and the whole construction hangs inside an indirect statement.',
  analysisIt: 'Si prenda il paragrafo 2 da solo ed è uno dei brani più preziosi del *Corpus Caesarianum*, perché non parla affatto di guerra. Parla di informazione: niente giornali, niente servizio postale, niente strade degne del nome, e così un popolo intero si procura le notizie fermando gli sconosciuti e spremendoli. Il dettaglio della folla che si stringe attorno a un mercante nella piazza del mercato è osservato con precisione, e in tutta la letteratura latina non esiste nulla di simile.\n\nOra si leggano il paragrafo 1 e il 3, che lo incorniciano. *Infirmitas*, *mobiles*, *novis rebus student* - incostanza, mutevolezza, appetito di rivolgimenti - è il lessico romano consueto per l\'inaffidabilità politica, e Cesare lo schiera tutto prima di aver offerto una sola prova. La conclusione precede l\'osservazione: *nihil his committendum existimavit*, non si doveva affidare loro nulla.\n\nQuesta è la forma dell\'intera digressione, e conviene vederla con chiarezza. Un dettaglio etnografico esatto è collocato fra un pregiudizio e una politica, e presta a entrambi la propria credibilità. Se i Galli davvero decidono le grandi questioni sulla base delle chiacchiere di mercato, allora non possono governarsi da soli, e qualcuno deve farlo al posto loro. Ogni generalizzazione di questo paragrafo svolge un lavoro politico.\n\nLa proposizione finale è anche la frase più cinica del libro IV, e la più moderna: *pleri ad voluntatem eorum ficta respondeant*, i più si inventano le cose per compiacere ciò che la folla vuole sentirsi dire. Sul piano grammaticale, si osservi *quorum eos in vestigio paenitere necesse est*: l\'impersonale *paenitet* vuole la persona all\'accusativo e la cosa di cui ci si pente al genitivo, e l\'intera costruzione sta dentro un discorso indiretto.'
},

{
  work: 'bg-iv', key: 'bg.4.14', prefix: '[14] ',
  citation: '(De Bello Gallico IV.14-15)',
  title: 'Four hundred and thirty thousand',
  titleIt: 'Quattrocentotrentamila',
  description: 'The Usipetes and Tencteri had crossed the Rhine and asked for land. Their leaders came to Caesar\'s camp to negotiate and were detained; the next morning he attacked their camp. This is the episode for which Cato proposed in the Senate that Caesar be handed over to the Germans.',
  descriptionIt: 'Gli Usipeti e i Tencteri avevano passato il Reno e chiesto delle terre. I loro capi vennero all\'accampamento di Cesare per trattare e furono trattenuti; la mattina dopo egli attaccò il loro campo. È l\'episodio per cui Catone propose in Senato che Cesare fosse consegnato ai Germani.',
  english: '> [14] **1.** Having drawn up a triple line and quickly completed a march of eight miles, he reached the enemy camp before the Germans could perceive what was happening. **2.** They, thrown into confusion by everything at once, by the speed of our arrival and by the departure of their own men, with no time given them either to take counsel or to take up arms, were at a loss whether it was better to lead their forces against the enemy, or to defend the camp, or to seek safety in flight. **3.** When their fear was betrayed by the noise and the running about, our soldiers, spurred on by the previous day\'s treachery, burst into the camp. **4.** There those who could quickly get to their weapons held out against our men for a little and joined battle among the wagons and the baggage; **5.** but the rest of the crowd, of children and women (for they had left home and crossed the Rhine with all their people), began to flee in all directions, and Caesar sent the cavalry to hunt them down.\n>\n> [15] **1.** The Germans, hearing shouting behind them and seeing their own people being killed, threw away their weapons, abandoned their standards, and flung themselves out of the camp; **2.** and when they had reached the meeting of the Meuse and the Rhine, despairing of further flight and with a great number already killed, the rest threw themselves into the river and there perished, overcome by fear, exhaustion and the force of the water. **3.** Our men, every one of them unhurt and with very few wounded, withdrew to camp out of the fear of so great a war, the enemy\'s numbers having been four hundred and thirty thousand persons. **4.** Caesar gave those he had kept in the camp permission to leave. **5.** They, fearing the punishments and tortures of the Gauls whose lands they had ravaged, said that they wished to remain with him. Caesar granted them their freedom.',
  italian: '> [14] **1.** Disposta la triplice linea e compiuta rapidamente una marcia di otto miglia, giunse all\'accampamento nemico prima che i Germani potessero accorgersi di che cosa stesse accadendo. **2.** Costoro, sconvolti all\'improvviso da ogni cosa, dalla rapidità del nostro arrivo e dalla partenza dei propri, senza che fosse loro concesso il tempo né di prendere decisioni né di impugnare le armi, non sapevano se fosse meglio condurre le truppe contro il nemico, o difendere il campo, o cercare salvezza nella fuga. **3.** Poiché il loro terrore si manifestava nel frastuono e nel correre qua e là, i nostri soldati, spronati dal tradimento del giorno prima, irruppero nell\'accampamento. **4.** Lì quelli che poterono impugnare in fretta le armi resistettero per poco ai nostri e attaccarono battaglia fra i carri e i bagagli; **5.** ma il resto della folla, di fanciulli e di donne (erano infatti usciti di casa e avevano passato il Reno con tutti i loro), cominciò a fuggire da ogni parte, e Cesare mandò la cavalleria a inseguirli.\n>\n> [15] **1.** I Germani, udite grida alle loro spalle e vedendo che i loro venivano uccisi, gettarono le armi, abbandonarono le insegne e si precipitarono fuori dall\'accampamento; **2.** e giunti alla confluenza della Mosa e del Reno, disperando di una fuga ulteriore e con un gran numero già ucciso, gli altri si gettarono nel fiume e lì perirono, sopraffatti dalla paura, dalla stanchezza e dalla forza della corrente. **3.** I nostri, tutti quanti incolumi e con pochissimi feriti, si ritirarono nell\'accampamento dal timore di una guerra così grande, essendo stato il numero dei nemici di quattrocentotrentamila persone. **4.** Cesare diede a quelli che aveva trattenuto nel campo la facoltà di andarsene. **5.** Quelli, temendo i supplizi e le torture dei Galli di cui avevano devastato i campi, dissero di voler restare presso di lui. Cesare concesse loro la libertà.',
  analysis: 'Read the two chapters for their bookkeeping, because that is how they are built. On one side of the ledger, *hostium numerus capitum CCCCXXX milium*: four hundred and thirty thousand people. On the other, *nostri ad unum omnes incolumes, perpaucis vulneratis*: not one Roman killed. Those two facts are placed in the same sentence, and the sentence is a report of a withdrawal to camp.\n\nThe words that carry the killing are all indirect. *Ad quos consectandos Caesar equitatum misit* - the object of *consectandos* is *puerorum mulierumque*, children and women, named in the previous clause and then never mentioned again. At the rivers the survivors *se in flumen praecipitaverunt atque ibi... perierunt*: they drowned themselves, grammatically speaking, and the Roman cavalry behind them is left in a subordinate clause. Nobody in these two chapters is ever the subject of a verb meaning "killed" except the Germans killing each other\'s hopes.\n\nAnd then the framing, which is the real subject. Section 14.3 gives the soldiers a motive: *pristini diei perfidia incitati*, spurred on by the previous day\'s treachery. The reader is invited to accept, in passing, that the treachery was the Germans\'; the leaders had come to negotiate and were being held in Caesar\'s camp when the attack went in. Section 15.4-5 then closes with an act of mercy - the detained men are offered their freedom and choose to stay - placed exactly where it will colour everything before it.\n\nCato was not persuaded. According to Plutarch he proposed in the Senate that Caesar be handed over to the Germans for attacking them during a truce, which is about as close as a Roman came to alleging a war crime; he was voted down, and a public thanksgiving was decreed instead. The number itself is almost certainly a population figure rather than a body count, and Caesar\'s own, which does not make it better. This chapter is the concrete case behind the note on framing at *De Bello Gallico* II.27-28.',
  analysisIt: 'Questi due capitoli vanno letti per la loro contabilità, perché è così che sono costruiti. Su un lato del registro, *hostium numerus capitum CCCCXXX milium*: quattrocentotrentamila persone. Sull\'altro, *nostri ad unum omnes incolumes, perpaucis vulneratis*: nemmeno un Romano ucciso. I due dati stanno nella stessa frase, e la frase è il resoconto di un rientro all\'accampamento.\n\nLe parole che portano la strage sono tutte indirette. *Ad quos consectandos Caesar equitatum misit*: l\'oggetto di *consectandos* è *puerorum mulierumque*, fanciulli e donne, nominati nella proposizione precedente e poi mai più. Ai fiumi i superstiti *se in flumen praecipitaverunt atque ibi... perierunt*: grammaticalmente si sono annegati da sé, e la cavalleria romana alle loro spalle resta in una subordinata. In questi due capitoli nessuno è mai soggetto di un verbo che significhi "uccidere", tranne i Germani che uccidono le proprie speranze.\n\nE poi la cornice, che è il vero argomento. Il paragrafo 14.3 dà ai soldati un movente: *pristini diei perfidia incitati*, spronati dal tradimento del giorno prima. Il lettore è invitato ad accettare di sfuggita che il tradimento fosse dei Germani; i loro capi erano venuti a trattare ed erano trattenuti nell\'accampamento di Cesare quando scattò l\'attacco. I paragrafi 15.4-5 chiudono poi con un atto di clemenza - ai trattenuti è offerta la libertà e scelgono di restare - collocato esattamente dove potrà colorare tutto ciò che precede.\n\nCatone non si lasciò convincere. Secondo Plutarco propose in Senato che Cesare fosse consegnato ai Germani per averli attaccati durante una tregua, che è quanto di più vicino a un\'accusa di crimine di guerra un Romano potesse formulare; fu messo in minoranza, e in luogo di ciò fu decretato un ringraziamento pubblico. La cifra è quasi certamente un dato di popolazione e non un conto dei morti, ed è di Cesare stesso, il che non la rende migliore. Questo capitolo è il caso concreto dietro la nota sulla cornice narrativa in *De Bello Gallico* II.27-28.'
},

{
  work: 'bg-iv', key: 'bg.4.17', prefix: '[17] ',
  citation: '(De Bello Gallico IV.17)',
  title: 'Ten days to bridge the Rhine',
  titleIt: 'Dieci giorni per gettare un ponte sul Reno',
  description: 'Caesar could have crossed the Rhine in boats. He explains, in one clause, why he would not, and then describes the bridge in enough detail that engineers have rebuilt it from this chapter alone. It is the hardest Latin in this batch by a wide margin.',
  descriptionIt: 'Cesare avrebbe potuto attraversare il Reno con delle barche. Spiega in una sola proposizione perché non volle, e poi descrive il ponte con tanta precisione che degli ingegneri lo hanno ricostruito basandosi solo su questo capitolo. È di gran lunga il latino più difficile di questo gruppo.',
  emend: [['Rhenum transire decrevat', 'Rhenum transire decreverat']],
  english: '> [17] **1.** Caesar, for the reasons I have mentioned, had decided to cross the Rhine; but he judged that crossing by boat was neither safe enough, nor consistent with his own dignity or that of the Roman people. **2.** And so, although the greatest difficulty in building a bridge was set before him, on account of the width, the speed and the depth of the river, he thought that he must nevertheless attempt it, or else not take his army across at all. **3.** He devised this plan for a bridge. He joined together pairs of piles a foot and a half thick, sharpened a little at the bottom and measured to the depth of the river, at an interval of two feet from each other. **4.** When he had lowered these into the river by machinery and fixed them and driven them home with pile-drivers, not upright like a post but sloping and leaning forward, so that they inclined with the current of the river, **5.** he set up two more opposite them, joined in the same way, at a distance of forty feet lower down, turned against the force and drive of the river. **6.** Both of these were then held apart by two-foot beams laid in above, the width of the joint between the piles, with a pair of braces at either end. **7.** With these held apart and lashed in opposite directions, the strength of the work was such, and the nature of the arrangement, that the greater the force of water that drove against it, the more tightly the parts were bound and held. **8.** These were covered over with timber laid straight across, and floored with poles and wickerwork. **9.** And no less were piles driven in obliquely on the downstream side, which, set under it like a ram and joined to the whole work, might take the force of the river, **10.** and others likewise a short space above the bridge, so that if tree trunks or ships were sent down by the natives to break the work, the force of these things might be lessened by such defences and they might do the bridge no harm.',
  italian: '> [17] **1.** Cesare, per le ragioni che ho ricordato, aveva deciso di passare il Reno; ma riteneva che attraversarlo con delle barche non fosse abbastanza sicuro, né lo giudicava conforme alla propria dignità o a quella del popolo romano. **2.** E così, benché gli si presentasse la massima difficoltà nel costruire un ponte, per la larghezza, la rapidità e la profondità del fiume, pensava che si dovesse comunque tentare, o altrimenti non far passare affatto l\'esercito. **3.** Ideò questo progetto di ponte. Univa fra loro, a una distanza di due piedi, coppie di pali spessi un piede e mezzo, appuntiti un poco in basso e misurati sulla profondità del fiume. **4.** Dopo averli calati nel fiume con delle macchine, averli fissati e conficcati con i battipalo, non a piombo come un palo ma inclinati e protesi in avanti, così da assecondare la corrente del fiume, **5.** ne piantava altri due di fronte, uniti allo stesso modo, a quaranta piedi di distanza più a valle, rivolti contro la forza e l\'impeto del fiume. **6.** Entrambe le coppie venivano poi tenute distanziate da travi di due piedi inserite dall\'alto, quanto era l\'ampiezza della giuntura fra i pali, con due morse a ciascuna estremità. **7.** Tenute così divaricate e legate in senso opposto, la solidità dell\'opera e la natura stessa dell\'assetto erano tali che quanto maggiore era la forza dell\'acqua che vi si scagliava contro, tanto più strettamente le parti restavano legate e trattenute. **8.** Il tutto veniva ricoperto da travi disposte per il lungo e pavimentato con pertiche e graticci. **9.** E non di meno si conficcavano pali obliqui sul lato a valle, i quali, posti sotto come un ariete e collegati a tutta l\'opera, ricevessero la forza del fiume, **10.** e altri parimenti poco più a monte del ponte, perché, se i barbari avessero fatto scendere tronchi d\'albero o imbarcazioni per abbattere l\'opera, la violenza di quelle cose fosse attenuata da simili difese e non nuocessero al ponte.',
  analysis: 'This is the chapter that breaks students, and it is worth knowing why. The difficulty is not syntactic - the periods are long but orderly - it is lexical and referential. *Tigna*, *sublicae*, *fistucae*, *fibulae*, *longurii*, *crates*, *transtra*: a dozen words of carpentry and pile-driving, most of them appearing once in a school career, and every one of them naming a thing the reader has to picture before the sentence will resolve. Add the pronouns - *haec*, *iis*, *quibus*, *eorum* - each pointing at a different piece of timber, and you have a paragraph that cannot be read at all until it is drawn.\n\nThe tenses are worth watching too. *Iungebat*, *statuebat*, *distinebantur*, *contexebantur*, *agebantur*: imperfects and imperfect passives throughout, because this is not a narrative of one day\'s work but the description of a repeated procedure. It is a specification, not a story.\n\nThe elegant part is section 7, and Caesar clearly enjoys it: *quo maior vis aquae se incitavisset, hoc artius inligata tenerentur* - the harder the river pushed, the more tightly the structure held. Upstream and downstream pile-pairs lean into each other, so the current tightens the joint instead of loosening it. The correlative *quo... hoc* with two comparatives is the sentence to memorise from this chapter.\n\nBut the reason for the whole thing is in section 1, not in the engineering. Boats would have worked. Caesar rejects them because crossing in boats was *neque suae neque populi Romani dignitatis* - beneath his dignity and Rome\'s. The bridge is a statement addressed to the Germans and, through this dispatch, to the Senate: Rome can put a road across the Rhine whenever it likes. It took ten days, the army walked over, stayed eighteen days, and Caesar then demolished it.\n\n**Textual note:** the Latin Library prints *Rhenum transire decrevat*. The app prints *decreverat*, the pluperfect the sense and every edition require; *decrevat* is not a form.',
  analysisIt: 'È il capitolo che spezza gli studenti, e vale la pena sapere perché. La difficoltà non è sintattica - i periodi sono lunghi ma ordinati - è lessicale e referenziale. *Tigna*, *sublicae*, *fistucae*, *fibulae*, *longurii*, *crates*, *transtra*: una dozzina di termini di carpenteria e di palificazione, quasi tutti destinati a comparire una volta sola in una carriera scolastica, e ciascuno dei quali nomina una cosa che il lettore deve visualizzare prima che la frase si sciolga. Si aggiungano i pronomi - *haec*, *iis*, *quibus*, *eorum* - ognuno dei quali punta a un pezzo di legname diverso, e si ottiene un paragrafo che non si può leggere finché non lo si disegna.\n\nVale la pena osservare anche i tempi. *Iungebat*, *statuebat*, *distinebantur*, *contexebantur*, *agebantur*: imperfetti e imperfetti passivi dall\'inizio alla fine, perché questa non è la narrazione del lavoro di un giorno ma la descrizione di una procedura ripetuta. È un capitolato, non un racconto.\n\nLa parte elegante è il paragrafo 7, e Cesare se la gode visibilmente: *quo maior vis aquae se incitavisset, hoc artius inligata tenerentur*, quanto più forte spingeva il fiume, tanto più saldamente la struttura teneva. Le coppie di pali di monte e di valle si appoggiano l\'una contro l\'altra, così la corrente serra la giuntura invece di allentarla. Il correlativo *quo... hoc* con due comparativi è la frase da mandare a memoria di questo capitolo.\n\nMa la ragione di tutta l\'impresa sta nel paragrafo 1, non nell\'ingegneria. Le barche avrebbero funzionato. Cesare le rifiuta perché passare in barca *neque suae neque populi Romani dignitatis*, non era degno né di lui né di Roma. Il ponte è una dichiarazione rivolta ai Germani e, attraverso questo dispaccio, al Senato: Roma può gettare una strada sul Reno quando le pare. Ci vollero dieci giorni, l\'esercito passò a piedi, rimase diciotto giorni, e Cesare poi lo demolì.\n\n**Nota testuale:** The Latin Library stampa *Rhenum transire decrevat*. L\'app stampa *decreverat*, il piuccheperfetto richiesto dal senso e da tutte le edizioni; *decrevat* non è una forma esistente.'
},

{
  work: 'bg-iv', key: 'bg.4.25', prefix: '[25] ',
  citation: '(De Bello Gallico IV.25)',
  title: 'Jump down, soldiers, unless you want to hand the eagle to the enemy',
  titleIt: 'Saltate giù, soldati, se non volete consegnare l\'aquila ai nemici',
  description: 'The landing in Britain has stalled. The water is deep, the shore is held, and the men will not go over the side. What follows is the only direct speech in this batch and one of the very few in the whole work, and Caesar gives it to a man whose name he does not record.',
  descriptionIt: 'Lo sbarco in Britannia si è arenato. L\'acqua è profonda, la riva è presidiata, e i soldati non vogliono scavalcare la murata. Quello che segue è l\'unico discorso diretto di questo gruppo e uno dei pochissimi di tutta l\'opera, e Cesare lo affida a un uomo di cui non registra il nome.',
  fix: [["' desilite', inquit, ' milites,", "'desilite', inquit, 'milites,"]],
  english: '> [25] **1.** When Caesar noticed this, he ordered the warships, whose appearance was less familiar to the natives and whose movement was readier for use, to be pulled a little away from the transports, driven on by the oars and stationed on the enemy\'s open flank, and the enemy to be driven off and dislodged from there with slings, arrows and artillery; and this was of great use to our men. **2.** For the natives, alarmed by the shape of the ships and the motion of the oars and the unfamiliar kind of artillery, halted and gave ground just a little. **3.** And while our soldiers hung back, chiefly because of the depth of the sea, the man who carried the eagle of the Tenth Legion, having called on the gods that the thing might turn out well for the legion, said: "Jump down, soldiers, unless you want to hand the eagle over to the enemy; I at any rate shall have done my duty to the republic and to my commander." **4.** When he had said this in a loud voice, he threw himself from the ship and began to carry the eagle towards the enemy. **5.** Then our men, urging one another on not to let so great a disgrace happen, all leapt from the ship together. **6.** And when the men in the nearest ships saw them, they too followed and came up close to the enemy.',
  italian: '> [25] **1.** Quando Cesare se ne accorse, ordinò che le navi da guerra, il cui aspetto era meno familiare ai barbari e il cui movimento più pronto all\'uso, fossero allontanate un poco dalle navi da carico, spinte a forza di remi e schierate sul fianco scoperto dei nemici, e che di lì i nemici fossero respinti e allontanati con fionde, frecce e macchine; e la cosa fu di grande utilità per i nostri. **2.** I barbari infatti, turbati dalla forma delle navi, dal movimento dei remi e da quel genere insolito di macchine, si fermarono e indietreggiarono di poco. **3.** E mentre i nostri soldati esitavano, soprattutto per la profondità del mare, colui che portava l\'aquila della Decima legione, invocati gli dèi perché la cosa riuscisse felicemente alla legione, disse: "Saltate giù, soldati, se non volete consegnare l\'aquila ai nemici; io per parte mia avrò fatto il mio dovere verso la repubblica e verso il comandante". **4.** Detto questo a gran voce, si gettò dalla nave e cominciò a portare l\'aquila contro i nemici. **5.** Allora i nostri, esortandosi a vicenda a non lasciar accadere un\'onta così grande, saltarono giù dalla nave tutti insieme. **6.** E quando quelli delle navi più vicine li videro, li seguirono anch\'essi e si avvicinarono ai nemici.',
  analysis: 'The astonishing thing here is the grammar, not the heroism. In seven books Caesar hardly ever uses direct speech - even his own great address to the mutinous army at *De Bello Gallico* I.40 is reported in the third person, at one remove - and when he finally breaks that rule, he does not break it for himself. He gives the only quoted words in the book to an *aquilifer* whose name he does not write down.\n\nRead what the man actually says. *Ego certe meum rei publicae atque imperatori officium praestitero*: a future perfect, "I at any rate shall have done my duty". The tense puts the act in the past before it has happened, which makes it unarguable - whatever the rest of you do, this will already be true of me. And the duty is owed to two things named in one breath and in a deliberate order: *rei publicae atque imperatori*, the republic and then the commander. A Roman reader in 55 BC would have heard that order. A Roman reader in 49 BC would have heard it very differently.\n\nNote also *obtestatus deos, ut ea res legioni feliciter eveniret*. He prays first, and not for himself but for the legion. Then the threat, which is not death: *nisi vultis aquilam hostibus prodere*. Losing the eagle was the worst thing that could happen to a legion, worse than being destroyed, so what he holds over them is shame. It works instantly, and section 5 says so in the same terms - *ne tantum dedecus admitteretur*.\n\nThe legion is the Tenth again: the one Caesar promised to march with alone at I.40, and the one he ran to first at II.21. Three books, three appearances, always at the moment the narrative needs a legion nobody has to be persuaded twice.\n\n**Source style:** the Latin Library prints the opening quotation marks with a space after them, *‘ desilite’, inquit, ‘ milites*. The app closes them up; nothing else is changed.',
  analysisIt: 'La cosa sorprendente qui è la grammatica, non l\'eroismo. In sette libri Cesare non usa quasi mai il discorso diretto - perfino il suo grande discorso all\'esercito sull\'orlo dell\'ammutinamento, in *De Bello Gallico* I.40, è riferito in terza persona, a distanza - e quando finalmente infrange quella regola non la infrange per sé. Affida le uniche parole citate del libro a un *aquilifer* di cui non scrive il nome.\n\nSi legga che cosa dice davvero quell\'uomo. *Ego certe meum rei publicae atque imperatori officium praestitero*: un futuro anteriore, "io per parte mia avrò fatto il mio dovere". Il tempo colloca l\'atto nel passato prima ancora che accada, e questo lo rende inoppugnabile: qualunque cosa facciate voi, di me sarà già vero. E il dovere è dovuto a due cose nominate in un fiato e in un ordine preciso: *rei publicae atque imperatori*, la repubblica e poi il comandante. Un lettore romano del 55 a.C. sentiva quell\'ordine. Un lettore romano del 49 a.C. lo sentiva in modo molto diverso.\n\nSi noti anche *obtestatus deos, ut ea res legioni feliciter eveniret*. Prima prega, e non per sé ma per la legione. Poi la minaccia, che non è la morte: *nisi vultis aquilam hostibus prodere*. Perdere l\'aquila era la cosa peggiore che potesse capitare a una legione, peggio dell\'annientamento, e quindi ciò che tiene sospeso sui compagni è la vergogna. Funziona all\'istante, e il paragrafo 5 lo dice con le stesse parole: *ne tantum dedecus admitteretur*.\n\nLa legione è di nuovo la Decima: quella con cui Cesare promise di marciare da solo in I.40 e quella da cui corse per prima in II.21. Tre libri, tre apparizioni, sempre nel momento in cui il racconto ha bisogno di una legione che non vada convinta due volte.\n\n**Stile della fonte:** The Latin Library stampa le virgolette di apertura seguite da uno spazio, *‘ desilite’, inquit, ‘ milites*. L\'app le chiude; nient\'altro è cambiato.'
},

{
  work: 'bg-iv', key: 'bg.4.33', prefix: '[33] ',
  citation: '(De Bello Gallico IV.33)',
  title: 'Running out along the pole at a gallop',
  titleIt: 'Correre sul timone al galoppo',
  description: 'The British war chariot, described with the close attention of a man who has just been badly surprised by one. Nobody in the Mediterranean had fought from a chariot for centuries, which is why Caesar has to explain it - and why this paragraph is the single most important source we have on it.',
  descriptionIt: 'Il carro da guerra britannico, descritto con l\'attenzione ravvicinata di chi ne è appena stato colto di sorpresa. Nel Mediterraneo nessuno combatteva più dal carro da secoli, ed è per questo che Cesare deve spiegarlo, ed è per questo che questo paragrafo è la fonte più importante che abbiamo in proposito.',
  english: '> [33] **1.** This is their manner of fighting from chariots. First they drive about in every direction and throw missiles, and by the very terror of the horses and the din of the wheels they generally throw the ranks into confusion; and when they have worked their way in among the squadrons of cavalry, they leap down from the chariots and fight on foot. **2.** The drivers meanwhile withdraw gradually from the fighting and place the chariots in such a way that, if the men are hard pressed by numbers, they have a clear line of retreat to their own side. **3.** Thus they provide the mobility of cavalry and the steadiness of infantry in battle, and by daily practice and training they achieve so much that they are accustomed to hold their horses at a gallop on a steep and sheer slope, to check and turn them in a moment, to run out along the pole, to stand on the yoke, and from there to get themselves back into the chariot with the greatest speed.',
  italian: '> [33] **1.** Questo è il loro modo di combattere dai carri. Dapprima corrono in ogni direzione e scagliano proiettili, e con il terrore stesso dei cavalli e il fragore delle ruote scompigliano di solito le file; e quando si sono insinuati fra gli squadroni di cavalleria, saltano giù dai carri e combattono a piedi. **2.** Gli aurighi intanto si ritirano a poco a poco dalla battaglia e dispongono i carri in modo tale che, se i loro sono premuti dalla massa dei nemici, abbiano una via di ritirata libera verso i propri. **3.** Assicurano così nei combattimenti la mobilità della cavalleria e la stabilità della fanteria, e con l\'esercizio quotidiano e l\'addestramento ottengono tanto da essere soliti trattenere i cavalli lanciati al galoppo su un pendio ripido e scosceso, frenarli e voltarli in un attimo, correre lungo il timone, stare ritti sul giogo e di lì rientrare nel carro con la massima rapidità.',
  analysis: 'Caesar stops the war to explain a machine. There is no narrative in this paragraph at all - no place, no date, no casualties - only a technology and how it is used, and that is itself the tell: the Roman army had run into something it did not have a doctrine for, and the dispatch has to teach the Senate what it was.\n\nThe structure is a manual. First what the chariots do (*primo per omnes partes perequitant*), then what the drivers do while the fighters are down (*aurigae interim*), then the thesis. That thesis is two words wide and perfectly balanced: *mobilitatem equitum, stabilitatem peditum* - the mobility of cavalry, the steadiness of infantry. Genitive plus abstract noun, twice, no verb between them. It is the kind of formulation a staff officer writes, and it explains in four words why a weapon everyone else had abandoned was still worth having.\n\nThen the last clause runs away with itself, and deliberately. Five infinitives after *consuerint*, each more showy than the last: hold a galloping team on a sheer slope, check and turn them, run out along the pole, stand on the yoke, drop back into the car at speed. The syntax is simple and the accumulation does the work; you can hear a professional soldier being impressed against his will.\n\nGreek and Roman armies had given up the war chariot centuries before this - it survives in Homer as a taxi to the battlefield, which is roughly what the British were using it for too. That gap is why Caesar had to write the paragraph, and why archaeologists reconstructing an Iron Age chariot still start from these nine lines.',
  analysisIt: 'Cesare ferma la guerra per spiegare una macchina. In questo paragrafo non c\'è narrazione alcuna - niente luogo, niente data, nessuna perdita - solo una tecnologia e il modo in cui viene usata, ed è già questo l\'indizio: l\'esercito romano si era imbattuto in qualcosa per cui non aveva una dottrina, e il dispaccio deve insegnare al Senato di che cosa si trattasse.\n\nLa struttura è quella di un manuale. Prima che cosa fanno i carri (*primo per omnes partes perequitant*), poi che cosa fanno gli aurighi mentre i combattenti sono a terra (*aurigae interim*), poi la tesi. Quella tesi è larga due parole ed è perfettamente bilanciata: *mobilitatem equitum, stabilitatem peditum*, la mobilità della cavalleria, la stabilità della fanteria. Genitivo più nome astratto, due volte, senza verbo in mezzo. È il tipo di formulazione che scrive un ufficiale di stato maggiore, e spiega in quattro parole perché un\'arma che tutti gli altri avevano abbandonato valesse ancora la pena.\n\nPoi l\'ultima proposizione prende il largo, e di proposito. Cinque infiniti dopo *consuerint*, ognuno più spettacolare del precedente: trattenere una pariglia al galoppo su un pendio a strapiombo, frenarla e voltarla, correre lungo il timone, stare ritti sul giogo, rientrare nel carro a tutta velocità. La sintassi è semplice e il lavoro lo fa l\'accumulo; si sente un soldato di mestiere restare impressionato suo malgrado.\n\nGli eserciti greci e romani avevano abbandonato il carro da guerra secoli prima: sopravvive in Omero come un taxi per il campo di battaglia, che è più o meno l\'uso che ne facevano anche i Britanni. È questa distanza che obbligò Cesare a scrivere il paragrafo, ed è per questo che gli archeologi che ricostruiscono un carro dell\'età del ferro partono ancora da queste nove righe.'
}

];
