/*
 * v1.11.4 - De Bello Gallico, Book VI, the last two (11 and 28), which closes
 * the book at its allocated 6. VI.11 opens the great ethnographic digression;
 * VI.28 closes it, and is the only chapter in seven books with no Romans in it.
 */
module.exports = [

{
  work: 'bg-vi', key: 'bg.6.11', prefix: '[11] ',
  citation: '(De Bello Gallico VI.11)',
  title: 'Two parties in every house in Gaul',
  titleIt: 'Due partiti in ogni casa della Gallia',
  description: 'The opening of the great ethnographic digression, and the most politically acute paragraph Caesar ever wrote about Gaul. Every state, every district, almost every household is split into two - and the last sentence explains, without meaning to, how the country was conquered.',
  descriptionIt: 'L\'apertura della grande digressione etnografica, e il paragrafo politicamente più acuto che Cesare abbia mai scritto sulla Gallia. Ogni nazione, ogni distretto, quasi ogni casa è divisa in due, e l\'ultima frase spiega, senza volerlo, come il paese sia stato conquistato.',
  emend: [['contra potentio rem', 'contra potentiorem']],
  english: '> [11] **1.** Since we have arrived at this point, it does not seem out of place to set out the customs of Gaul and Germany, and how these nations differ from one another. **2.** In Gaul there are parties not only in every state and in every district and division, but almost in individual households as well; **3.** and the leaders of those parties are the men who in the judgement of their followers are thought to carry the greatest weight, to whose decision and judgement the whole of every matter and every plan comes back. **4.** And this seems to have been established of old for the following reason: that nobody from the common people should lack help against a more powerful man. For each man does not allow his own people to be oppressed and cheated, and if he acts otherwise he has no standing among his own. **5.** This same principle holds for Gaul as a whole: for all the states are divided into two parties.',
  italian: '> [11] **1.** Poiché siamo giunti a questo punto, non sembra fuori luogo esporre i costumi della Gallia e della Germania e in che cosa queste nazioni differiscano fra loro. **2.** In Gallia esistono fazioni non soltanto in ogni nazione e in ogni distretto e circoscrizione, ma quasi anche nelle singole case; **3.** e capi di quelle fazioni sono gli uomini che a giudizio dei loro seguaci sono ritenuti avere la massima autorità, alla cui decisione e al cui giudizio si rimette l\'insieme di ogni questione e di ogni deliberazione. **4.** E questo sembra essere stato stabilito anticamente per la ragione seguente: che nessuno del popolo restasse privo di aiuto contro un più potente. Ciascuno infatti non permette che i suoi vengano oppressi e raggirati, e se agisce altrimenti non ha alcuna autorità presso i propri. **5.** Lo stesso principio vale per la Gallia nel suo complesso: tutte le nazioni infatti sono divise in due partiti.',
  analysis: 'The chapter opens with the editorial voice, not the narrative one: *quoniam ad hunc locum perventum est, non alienum esse videtur... proponere*. That is the narrator of the book stepping out of the story to explain why the next twenty chapters are about ethnography rather than about a war - the same voice as *quas commemoravi* at *De Bello Gallico* IV.17, and it never says anything about Caesar the general.\n\nWhat follows is the best piece of political analysis in the work. Factions everywhere, and not only at the level of the state: *paene etiam in singulis domibus*, almost in individual households. Leaders defined not by office but by whose judgement carries weight. And then a functional explanation, which is what makes it analysis rather than description: the system exists *ne quis ex plebe contra potentiorem auxili egeret*, so that no commoner is left without support against a stronger man, and a patron who fails to protect his people loses his standing among them.\n\nThat is Roman *clientela*, described in Roman terms without the word being used - protection exchanged for support, and reputation as the enforcement mechanism. Whether Gaul actually worked like this, or whether Caesar recognised Roman politics wherever he looked, cannot be settled from this text alone. He is, after all, a man whose own power rested on exactly such a network.\n\nThe last sentence is the operative one, and it is dropped in as though it were a footnote: *omnes civitates in partes divisae sunt duas*. A country in which every unit, down to the household, is already split in two is a country that can be taken a faction at a time - which is precisely how it was taken, beginning with the Aedui in Book I and running through every alliance in the seven books. Caesar does not say so. It is the technique of IV.5 and VI.16 once more: supply the premise, and let the reader do the work.\n\n**Textual note:** the Latin Library prints *contra potentio rem auxili egeret*, splitting a word across a space. The app prints *contra potentiorem*.',
  analysisIt: 'Il capitolo si apre con la voce editoriale, non con quella narrativa: *quoniam ad hunc locum perventum est, non alienum esse videtur... proponere*. È il narratore del libro che esce dalla storia per spiegare perché i venti capitoli successivi parlino di etnografia e non di guerra: la stessa voce di *quas commemoravi* nel *De Bello Gallico* IV.17, e non dice mai nulla su Cesare comandante.\n\nCiò che segue è il miglior pezzo di analisi politica dell\'opera. Fazioni dappertutto, e non solo a livello di nazione: *paene etiam in singulis domibus*, quasi anche nelle singole case. Capi definiti non da una carica ma dal peso del proprio giudizio. E poi una spiegazione funzionale, che è ciò che ne fa un\'analisi e non una descrizione: il sistema esiste *ne quis ex plebe contra potentiorem auxili egeret*, perché nessuno del popolo resti senza sostegno contro chi è più forte, e un patrono che non protegge i suoi perde autorità presso di loro.\n\nÈ la *clientela* romana, descritta in termini romani senza che la parola venga pronunciata: protezione in cambio di sostegno, con la reputazione come meccanismo di garanzia. Se la Gallia funzionasse davvero così, oppure se Cesare riconoscesse la politica romana ovunque guardasse, non è decidibile da questo testo. È pur sempre un uomo il cui potere poggiava esattamente su una rete di quel tipo.\n\nL\'ultima frase è quella operativa, ed è buttata lì come fosse una nota a piè di pagina: *omnes civitates in partes divisae sunt duas*. Un paese in cui ogni unità, fino alla casa, è già divisa in due è un paese che si può prendere una fazione alla volta, che è esattamente il modo in cui fu preso, a partire dagli Edui nel libro I e attraverso ogni alleanza dei sette libri. Cesare non lo dice. È di nuovo la tecnica di IV.5 e VI.16: fornire la premessa e lasciare il lavoro al lettore.\n\n**Nota testuale:** The Latin Library stampa *contra potentio rem auxili egeret*, spezzando una parola con uno spazio. L\'app stampa *contra potentiorem*.'
},

{
  work: 'bg-vi', key: 'bg.6.28', prefix: '[28] ',
  citation: '(De Bello Gallico VI.28)',
  title: 'A little smaller than an elephant',
  titleIt: 'Poco più piccoli di un elefante',
  description: 'The last of the three fabulous animals of the Hercynian forest, and the only chapter in seven books with no Romans in it at all. The aurochs was entirely real; the last one died in a Polish forest in 1627, so this is a window on an animal nobody will ever see.',
  descriptionIt: 'L\'ultimo dei tre animali favolosi della selva Ercinia, e l\'unico capitolo di sette libri in cui non compaia un solo Romano. L\'uro era del tutto reale: l\'ultimo morì in una foresta polacca nel 1627, e questa è dunque una finestra su un animale che nessuno vedrà mai.',
  english: '> [28] **1.** There is a third kind, of those which are called aurochs. These are a little below elephants in size, and in appearance and colour and shape they are bulls. **2.** Their strength is great and their speed is great, and they spare neither man nor beast once they have caught sight of them. **3.** These the natives eagerly trap in pits and kill. By this labour the young men harden themselves and train themselves with this kind of hunting, and those who have killed the most of them win great praise when they bring the horns back in public as evidence. **4.** But they cannot be made used to men and tamed, not even when taken very young. **5.** The size and shape and appearance of their horns differ greatly from the horns of our cattle. **6.** These they eagerly collect, edge them with silver at the rim, and use them as cups at their greatest feasts.',
  italian: '> [28] **1.** C\'è un terzo genere, quello degli animali chiamati uri. Sono di grandezza poco inferiore agli elefanti, e per aspetto, colore e forma sono tori. **2.** La loro forza è grande e grande la loro velocità, e non risparmiano né uomo né bestia che abbiano scorto. **3.** Li catturano con accanimento in fosse e li uccidono. Con questa fatica i giovani si induriscono e si addestrano con questo genere di caccia, e quelli che ne hanno uccisi di più ottengono grande lode quando ne riportano in pubblico le corna come prova. **4.** Ma non si possono abituare all\'uomo né addomesticare, nemmeno presi piccolissimi. **5.** La grandezza, la forma e l\'aspetto delle loro corna differiscono molto dalle corna dei nostri buoi. **6.** Le raccolgono con cura, le rivestono d\'argento all\'orlo e le usano come coppe nei banchetti più solenni.',
  analysis: 'It is worth asking what this paragraph is doing in a war report. It is the third of three animals - the reindeer, the elk and the aurochs - and the three together are the only stretch in seven books with no Roman in them anywhere. Some editors have suspected the whole digression of being an interpolation; most now accept it, partly because the detail is too good.\n\nStart with the detail that is wrong. *Magnitudine paulo infra elephantos* is an exaggeration: a bull aurochs stood about 1.8 metres at the shoulder, which is very large for cattle and nothing like an elephant. Now the details that are right. *Specie et colore et figura tauri* - it was a bull, because the aurochs, *Bos primigenius*, is the wild ancestor of domestic cattle. The temper is right; so is the refusal to tame, which is why domestication took thousands of years and selective breeding. And the horns are right: enormous, forward-curving, nothing like the horns of Mediterranean cattle.\n\nThe last sentence is the best evidence in the chapter, and it is the kind that cannot be invented: *ab labris argento circumcludunt atque in amplissimis epulis pro poculis utuntur* - the rim mounted in silver, used as drinking cups at the greatest feasts. Silver-mounted drinking horns turn up in Iron Age graves across northern Europe, and they look exactly like this. Somebody who told Caesar about the aurochs had held one in his hands.\n\nThe hunting belongs with *De Bello Gallico* VI.21 and its austerity programme: *hoc se labore durant adulescentes*, the young men harden themselves by it, and the horns go *in publicum* as proof of the kill. It is a rite of passage described as a training regime, which is how Caesar sees everything Germanic.\n\nAnd there is a melancholy that Caesar could not have intended. The aurochs survived in Europe for another sixteen centuries and then stopped: the last known animal died in the Jaktorów forest in Poland in 1627. This chapter is one of the fullest descriptions we have of a creature that no living person has seen.',
  analysisIt: 'Vale la pena chiedersi che cosa ci faccia questo paragrafo in un rapporto di guerra. È il terzo di tre animali - la renna, l\'alce e l\'uro - e i tre insieme sono l\'unico tratto di sette libri in cui non compaia un Romano da nessuna parte. Qualche editore ha sospettato che l\'intera digressione fosse un\'interpolazione; oggi la maggior parte l\'accetta, anche perché i dettagli sono troppo buoni.\n\nSi cominci dal dettaglio sbagliato. *Magnitudine paulo infra elephantos* è un\'esagerazione: un uro maschio raggiungeva circa un metro e ottanta al garrese, moltissimo per un bovino e niente affatto un elefante. Ora i dettagli giusti. *Specie et colore et figura tauri*: era un toro, perché l\'uro, *Bos primigenius*, è l\'antenato selvatico dei bovini domestici. Il carattere è esatto; lo è anche l\'impossibilità di addomesticarlo, ed è il motivo per cui la domesticazione richiese millenni e selezione. E le corna sono esatte: enormi, ricurve in avanti, nulla a che vedere con quelle dei bovini mediterranei.\n\nL\'ultima frase è la prova migliore del capitolo, ed è del tipo che non si può inventare: *ab labris argento circumcludunt atque in amplissimis epulis pro poculis utuntur*, l\'orlo rivestito d\'argento, usate come coppe nei banchetti più solenni. Corni potori con montatura d\'argento compaiono nelle tombe dell\'età del ferro in tutto il nord Europa, e sono esattamente così. Qualcuno, fra quelli che parlarono a Cesare dell\'uro, ne aveva tenuto uno in mano.\n\nLa caccia sta insieme al *De Bello Gallico* VI.21 e al suo programma di austerità: *hoc se labore durant adulescentes*, i giovani si temprano con questa fatica, e le corna vanno *in publicum* come prova dell\'uccisione. È un rito di passaggio descritto come un piano di addestramento, che è il modo in cui Cesare vede qualunque cosa germanica.\n\nE c\'è una malinconia che Cesare non poteva prevedere. L\'uro sopravvisse in Europa per altri sedici secoli e poi si fermò: l\'ultimo esemplare noto morì nella foresta di Jaktorów, in Polonia, nel 1627. Questo capitolo è una delle descrizioni più complete che possediamo di una creatura che nessun vivente ha mai visto.'
}

];
