/*
 * v1.11.3 - De Bello Gallico, Book III (3). The Veneti war: the ships, the
 * battle, the reprisal. Latin comes from batch/passages1113.json, extracted
 * verbatim; translations carry the chapter marker and the subsection numbers.
 */
module.exports = [

{
  work: 'bg-iii', key: 'bg.3.13', prefix: '[13] ',
  citation: '(De Bello Gallico III.13)',
  title: 'The ships that Roman rams could not hurt',
  titleIt: 'Le navi che i rostri romani non potevano scalfire',
  description: 'Caesar\'s fleet has met something it was not built for. Before the battle he stops the narrative and describes the enemy\'s ships piece by piece, and the description doubles as an admission: on the open Atlantic the Roman navy was outclassed.',
  descriptionIt: 'La flotta di Cesare ha incontrato qualcosa per cui non era stata costruita. Prima della battaglia egli ferma il racconto e descrive le navi nemiche pezzo per pezzo, e la descrizione vale anche come ammissione: sull\'Atlantico aperto la marina romana era inferiore.',
  english: '> [13] **1.** For their ships had been built and fitted out in this fashion: their keels were considerably flatter than those of our ships, so that they could more easily cope with the shallows and the ebb of the tide; **2.** their prows were quite upright, and their sterns likewise, adapted to the size of the waves and the storms; **3.** the ships were made entirely of oak, to endure any force and rough handling; **4.** their cross-benches were of beams a foot thick, fastened with iron nails as thick as a thumb; **5.** their anchors were secured with iron chains instead of ropes; **6.** they used hides and thinly dressed leather in place of sails, [these] either because they had no flax and no knowledge of its use, or, which is more likely, because they thought that such storms of the Ocean and such violence of the winds could not be withstood, and ships of such burden handled, by sails, and not conveniently enough. **7.** Our fleet\'s engagement with these ships was of such a kind that it had the advantage in speed alone and in the drive of the oars, while everything else, given the nature of the place and the violence of the storms, suited them better. **8.** For our ships could not damage them with the ram (so great was their solidity), nor could a missile easily be thrown up at them because of their height, and for the same reason they were less conveniently held with grappling irons. **9.** There was this too, that when [the wind had begun to blow hard and] they had given themselves to the wind, they both rode out the weather more easily and grounded on the shallows more safely, and when left by the tide had nothing to fear from rocks and reefs; all of which our ships had every reason to dread.',
  italian: '> [13] **1.** Le loro navi infatti erano costruite e attrezzate in questo modo: le chiglie erano assai più piatte delle nostre, perché potessero affrontare più facilmente i bassi fondali e il riflusso della marea; **2.** le prore erano molto ritte, e così anche le poppe, adattate all\'altezza dei flutti e alle tempeste; **3.** le navi erano fatte interamente di quercia, per sopportare qualsiasi urto e maltrattamento; **4.** i banchi erano di travi spesse un piede, fissate con chiodi di ferro grossi come un pollice; **5.** le ancore erano assicurate con catene di ferro invece che con funi; **6.** al posto delle vele usavano pelli e cuoio conciato sottile, [queste] o perché mancavano di lino e non ne conoscevano l\'uso, oppure, il che è più verosimile, perché ritenevano che tempeste dell\'Oceano tanto grandi e simili impeti di vento non si potessero sostenere, e navi di tale portata governare, con le vele, e non abbastanza comodamente. **7.** Lo scontro della nostra flotta con queste navi era tale che essa aveva il vantaggio soltanto nella velocità e nella spinta dei remi, mentre tutto il resto, data la natura del luogo e la violenza delle tempeste, era più adatto e più conveniente per loro. **8.** Le nostre non potevano infatti danneggiarle con il rostro (tanta era la loro solidità), né si riusciva facilmente a scagliare un proiettile fin lassù per via dell\'altezza, e per la stessa ragione erano trattenute meno agevolmente dai grappini. **9.** Si aggiungeva che, quando [il vento aveva cominciato a infuriare e] si erano affidate al vento, sopportavano meglio la tempesta, si arenavano più sicure sui bassi fondali e, abbandonate dalla marea, non temevano affatto scogli e rupi: tutte cose che le nostre navi avevano ogni ragione di temere.',
  analysis: 'This is technical ethnography, and it is where Caesar suddenly becomes lexically difficult. *Carinae*, *prorae*, *puppes*, *transtra*, *ancorae*, *aluta*, *cautes*: a whole nautical glossary arrives in one paragraph, most of it words a student will never have met, and the syntax offers no help because there is almost none. Sections 1 to 6 are a catalogue in asyndeton - part, material, purpose - with the verb *erant* stated once at the start and then simply understood six times over.\n\nSection 6 is the passage worth stopping at. Caesar gives two reasons the Veneti used leather instead of canvas, and marks one as better than the other: *sive propter inopiam lini... sive eo, quod est magis veri simile*. He is weighing evidence in public and telling the reader which way he leans. It happens very seldom in these books, and it is a reminder that the flat reporting voice everywhere else is a choice, not an incapacity.\n\nAnd then read sections 7 to 9 for what they concede. The Roman fleet is faster and better rowed, and that is the whole of its advantage; on everything that matters in Atlantic weather - hull strength, height, behaviour in shallows, survival when the tide leaves you - the enemy is better. *Quarum rerum omnium nostris navibus casus erat extimescendus*: our ships had to fear every one of these things. Caesar has just explained, in his own dispatch to the Senate, that his navy was outclassed. He can afford it, because the next chapter explains how he won anyway.\n\n**[hae]** and **[saevire ventus coepisset et]** stand in square brackets as editorial supplements: the manuscripts are unsatisfactory at both points and editors add the words to make the sentence run. The app prints them as the source does.',
  analysisIt: 'È etnografia tecnica, ed è il punto in cui Cesare diventa improvvisamente difficile sul piano lessicale. *Carinae*, *prorae*, *puppes*, *transtra*, *ancorae*, *aluta*, *cautes*: un intero glossario nautico arriva in un paragrafo solo, quasi tutto fatto di parole che uno studente non ha mai incontrato, e la sintassi non aiuta perché quasi non c\'è. I paragrafi da 1 a 6 sono un catalogo in asindeto - parte, materiale, scopo - con il verbo *erant* espresso una volta all\'inizio e poi semplicemente sottinteso sei volte.\n\nIl paragrafo 6 merita una sosta. Cesare dà due ragioni per cui i Veneti usavano cuoio invece di tela, e indica quale delle due gli pare migliore: *sive propter inopiam lini... sive eo, quod est magis veri simile*. Sta pesando le prove in pubblico e dice al lettore da che parte pende. Accade molto di rado in questi libri, ed è un promemoria: la voce piatta e referente di tutto il resto è una scelta, non un\'incapacità.\n\nPoi si leggano i paragrafi da 7 a 9 per ciò che concedono. La flotta romana è più veloce e meglio remata, e in questo si esaurisce il suo vantaggio; su tutto ciò che conta con il tempo atlantico - robustezza dello scafo, altezza, comportamento sui bassi fondali, sopravvivenza quando la marea ti abbandona - il nemico è migliore. *Quarum rerum omnium nostris navibus casus erat extimescendus*: le nostre navi dovevano temere ognuna di queste cose. Cesare ha appena spiegato, in un dispaccio destinato al Senato, che la sua marina era inferiore. Se lo può permettere, perché il capitolo successivo spiega come vinse lo stesso.\n\n**[hae]** e **[saevire ventus coepisset et]** stanno fra parentesi quadre come integrazioni editoriali: in entrambi i punti i manoscritti sono insoddisfacenti e gli editori aggiungono le parole per far correre la frase. L\'app le stampa come fa la fonte.'
},

{
  work: 'bg-iii', key: 'bg.3.14', prefix: '[14] ',
  citation: '(De Bello Gallico III.14)',
  title: 'A siege hook on a pole wins a sea battle',
  titleIt: 'Una falce da assedio su un palo vince una battaglia navale',
  description: 'Two hundred and twenty Veneti ships come out of harbour and the Roman officers openly have no idea what to do. The answer turns out to be a piece of siege equipment used at sea, and the battle is fought in front of an audience seated on the hills.',
  descriptionIt: 'Duecentoventi navi venete escono dal porto e gli ufficiali romani apertamente non sanno che fare. La risposta si rivela essere un attrezzo da assedio usato in mare, e la battaglia si combatte davanti a un pubblico seduto sulle colline.',
  english: '> [14] **1.** After storming several strongholds Caesar, when he understood that so much labour was being spent for nothing, and that the enemy\'s flight could not be checked nor any harm done to them by taking their towns, decided to wait for the fleet. **2.** When it had assembled and was first sighted by the enemy, about two hundred and twenty of their ships, fully prepared and equipped with every kind of gear, came out of harbour and took station facing ours; **3.** and it was not at all clear to Brutus, who commanded the fleet, nor to the military tribunes and centurions to whom the individual ships had been assigned, what they should do or what tactics they should adopt. **4.** For they had learned that no harm could be done with the ram; and although towers were raised, even so the height of the barbarian ships\' sterns overtopped them, so that missiles could not be thrown up conveniently enough from the lower position, while those launched by the Gauls came down with more force. **5.** One thing our men had prepared was of great use: sharpened hooks set into and fixed onto long poles, not unlike the shape of siege hooks. **6.** When with these the ropes that fastened the yards to the masts had been caught and drawn tight, they were snapped by driving the ship on with the oars. **7.** Once these were cut through the yards necessarily came down, so that, since all the hope of the Gallic ships lay in their sails and rigging, with these torn away all use of the ships was torn away at a stroke. **8.** What was left of the contest rested on courage, in which our soldiers easily had the better, and all the more because the thing was being done in the sight of Caesar and of the whole army, so that no act of any bravery could stay hidden; **9.** for all the hills and higher ground, from which there was a near view down onto the sea, were held by the army.',
  italian: '> [14] **1.** Espugnate parecchie roccaforti, Cesare, quando capì che si spendeva tanta fatica per nulla e che con la presa delle città non si arrestava la fuga dei nemici né si poteva far loro alcun danno, decise di aspettare la flotta. **2.** Quando questa si radunò e fu avvistata per la prima volta dai nemici, circa duecentoventi loro navi, del tutto pronte e fornite di ogni genere di attrezzatura, uscirono dal porto e si schierarono di fronte alle nostre; **3.** e né a Bruto, che comandava la flotta, né ai tribuni militari e ai centurioni ai quali erano state assegnate le singole navi era affatto chiaro che cosa fare o quale tattica adottare. **4.** Avevano infatti appreso che con il rostro non si poteva fare alcun danno; e per quanto si innalzassero torri, l\'altezza delle poppe delle navi barbariche le superava lo stesso, sicché dalla posizione più bassa non si riuscivano a scagliare proiettili con sufficiente efficacia, mentre quelli lanciati dai Galli arrivavano con più forza. **5.** Una cosa preparata dai nostri fu di grande utilità: falci affilate innestate e fissate su lunghe pertiche, di forma non dissimile dalle falci murali. **6.** Quando con queste si erano agganciate e tirate le funi che fissavano i pennoni agli alberi, le si spezzava spingendo la nave con i remi. **7.** Recise quelle, i pennoni cadevano necessariamente, sicché, poiché ogni speranza delle navi galliche stava nelle vele e nel sartiame, tolti questi veniva tolto in un colpo solo ogni uso delle navi. **8.** Ciò che restava dello scontro era affidato al valore, nel quale i nostri soldati avevano facilmente la meglio, e tanto più perché la cosa si svolgeva sotto gli occhi di Cesare e di tutto l\'esercito, così che nessuna azione un poco coraggiosa poteva restare nascosta; **9.** tutte le colline infatti e i luoghi più elevati, da cui si aveva una vista ravvicinata sul mare, erano occupati dall\'esercito.',
  analysis: 'Section 3 is remarkable for what a commander is willing to print. *Neque satis Bruto... constabat quid agerent aut quam rationem pugnae insisterent*: the admiral and every officer in the fleet were at a loss. Caesar could have left it out. Leaving it in makes the solution worth something, and it is a technique he uses constantly - the difficulty stated at full strength first, so that the answer lands.\n\nThe answer is not a naval invention at all. A *falx muralis* is a siege tool, a hooked blade for pulling stones out of a wall, and somebody has bolted one to a long pole and taken it to sea. The mechanism is described in one dry conditional sequence and the consequence in a single ruthless clause: *omnis usus navium uno tempore eriperetur*. A fleet that cannot be rammed, boarded or shot at is beaten by cutting its ropes.\n\nThen the closing image, which is why this chapter belongs next to *De Bello Gallico* II.25. There the men fought harder *in conspectu imperatoris*, in the sight of their commander. Here the entire army is watching from the hills - *omnes enim colles ac loca superiora... ab exercitu tenebantur* - and Caesar says outright what that is worth: *ut nullum paulo fortius factum latere posset*, no act of courage could go unnoticed. The bay becomes a theatre, the army becomes the audience, and courage becomes a performance with witnesses. It is the same claim about Roman *virtus* twice in two books, and the second time he has arranged the seating.',
  analysisIt: 'Il paragrafo 3 è notevole per ciò che un comandante accetta di mettere per iscritto. *Neque satis Bruto... constabat quid agerent aut quam rationem pugnae insisterent*: l\'ammiraglio e tutti gli ufficiali della flotta non sapevano che fare. Cesare avrebbe potuto ometterlo. Lasciarlo rende preziosa la soluzione, ed è una tecnica che usa di continuo: prima la difficoltà enunciata a piena forza, perché poi la risposta arrivi con peso.\n\nLa risposta non è affatto un\'invenzione navale. La *falx muralis* è uno strumento d\'assedio, una lama ricurva per strappare pietre da un muro, e qualcuno l\'ha imbullonata su una lunga pertica e portata in mare. Il meccanismo è descritto in un\'asciutta sequenza condizionale e la conseguenza in un\'unica proposizione spietata: *omnis usus navium uno tempore eriperetur*. Una flotta che non si può speronare, abbordare né bersagliare viene battuta tagliandole le funi.\n\nPoi l\'immagine finale, ed è il motivo per cui questo capitolo sta accanto al *De Bello Gallico* II.25. Là gli uomini combattevano meglio *in conspectu imperatoris*, sotto gli occhi del comandante. Qui è l\'intero esercito a guardare dalle colline - *omnes enim colles ac loca superiora... ab exercitu tenebantur* - e Cesare dice apertamente quanto valga: *ut nullum paulo fortius factum latere posset*, nessun atto di coraggio poteva passare inosservato. La baia diventa un teatro, l\'esercito diventa il pubblico, e il coraggio diventa una prestazione con testimoni. È la stessa affermazione sulla *virtus* romana per la seconda volta in due libri, e la seconda volta ha disposto lui i posti a sedere.'
},

{
  work: 'bg-iii', key: 'bg.3.16', prefix: '[16] ',
  citation: '(De Bello Gallico III.16)',
  title: 'The whole senate executed, the rest sold',
  titleIt: 'Tutto il senato giustiziato, il resto venduto',
  description: 'Five sentences that end a war and a people. Read it directly against the surrender of the Nervii in Book II, where Caesar spared everyone so that his mercy might be seen: here is the same instrument at its other setting, and he states the reasoning just as plainly.',
  descriptionIt: 'Cinque frasi che chiudono una guerra e un popolo. Va letto direttamente contro la resa dei Nervi nel libro II, dove Cesare risparmiò tutti perché la sua clemenza fosse vista: qui c\'è lo stesso strumento all\'altra regolazione, e la motivazione è enunciata con la stessa freddezza.',
  english: '> [16] **1.** By this battle the war against the Veneti and the whole seaboard was finished. **2.** For since all their young men, and all the older men too in whom there was any judgement or standing, had gathered there, and since they had brought together into one place whatever ships there were anywhere, **3.** with these lost the rest had nowhere to withdraw to and no way of defending their towns. **4.** So they surrendered themselves and all they had to Caesar. Upon them Caesar decided that punishment must fall the more heavily, so that the rights of envoys should be observed the more carefully by barbarians in time to come. So, having put the whole senate to death, he sold the rest under the garland.',
  italian: '> [16] **1.** Con questa battaglia la guerra contro i Veneti e contro tutta la fascia costiera fu conclusa. **2.** Poiché infatti tutti i loro giovani, e anche tutti gli uomini più anziani nei quali vi fosse un poco di senno o di autorità, si erano radunati là, e poiché avevano riunito in un solo luogo quante navi vi fossero in ogni dove, **3.** perdute quelle, i superstiti non avevano né dove ritirarsi né come difendere le proprie città. **4.** Perciò consegnarono se stessi e tutti i loro beni a Cesare. Contro di loro Cesare decise che si dovesse procedere tanto più duramente, affinché in futuro il diritto degli ambasciatori fosse osservato con maggiore scrupolo dai barbari. E così, messo a morte tutto il senato, vendette gli altri sotto la corona.',
  analysis: 'The whole moral weight of the chapter sits in one correlative: *eo gravius... quo diligentius*. The heavier the punishment, the more carefully the rule will be kept afterwards. That is deterrence stated as an equation, and Caesar states it in a purpose clause as though it were a matter of administration rather than a decision to kill an aristocracy.\n\nThe legal pretext is real, and it is the point of *ius legatorum*: the Veneti had detained Roman officers sent to requisition grain, and holding envoys was an offence against something Romans regarded as close to sacred. Note how much work that phrase does. It converts a war of conquest into the enforcement of a norm, and it converts the killing of a people\'s entire governing class into a lesson in international law.\n\nThen *omni senatu necato reliquos sub corona vendidit*. Five words. *Sub corona vendere* is the technical formula: prisoners of war were sold wearing a garland, which is how a buyer knew what he was buying. The ablative absolute disposes of the senate in two words and the main verb disposes of everybody else.\n\nSet this beside *De Bello Gallico* II.28, where the Nervii surrendered and Caesar preserved them *diligentissime*, *ut in miseros ac supplices usus misericordia videretur* - so that he might be seen to have used mercy. The two chapters are the same instrument at its two settings, and in both he gives the reason in a purpose clause. Mercy when mercy is useful, extermination when the example is useful. Neither is a mood.',
  analysisIt: 'Tutto il peso morale del capitolo sta in un correlativo: *eo gravius... quo diligentius*. Quanto più dura la punizione, tanto più scrupolosamente la regola sarà osservata in seguito. È la deterrenza enunciata come un\'equazione, e Cesare la enuncia in una finale come se fosse una questione amministrativa e non la decisione di uccidere un\'aristocrazia.\n\nIl pretesto giuridico è reale, ed è il senso di *ius legatorum*: i Veneti avevano trattenuto ufficiali romani mandati a requisire grano, e trattenere ambasciatori era un\'offesa a qualcosa che i Romani consideravano quasi sacro. Si osservi quanto lavoro fa quell\'espressione. Trasforma una guerra di conquista nell\'applicazione di una norma, e trasforma l\'eliminazione dell\'intera classe dirigente di un popolo in una lezione di diritto internazionale.\n\nPoi *omni senatu necato reliquos sub corona vendidit*. Cinque parole. *Sub corona vendere* è la formula tecnica: i prigionieri di guerra si vendevano con una corona in capo, ed era così che l\'acquirente sapeva che cosa stava comprando. L\'ablativo assoluto liquida il senato in due parole e il verbo principale liquida tutti gli altri.\n\nSi metta accanto al *De Bello Gallico* II.28, dove i Nervi si arresero e Cesare li conservò *diligentissime*, *ut in miseros ac supplices usus misericordia videretur*, perché apparisse aver usato misericordia. I due capitoli sono lo stesso strumento nelle sue due regolazioni, e in entrambi la ragione è data in una finale. Clemenza quando la clemenza è utile, sterminio quando è utile l\'esempio. Nessuno dei due è uno stato d\'animo.'
}

];
