/*
 * v1.11.1 - De Bello Gallico, Book I (6). Latin is never typed here: each item
 * names a key in batch/passages1111.json, extracted verbatim from the cache.
 * The translations carry the chapter marker and the bold subsection numbers so
 * all three texts line up; the Latin's markers are added afterwards by
 * tools/mark_sections.js from the Perseus boundaries.
 */
module.exports = [

{
  work: 'bg-i', key: 'bg.1.1', prefix: '[1] ',
  citation: '(De Bello Gallico I.1)',
  title: 'The most famous first sentence in Latin',
  titleIt: 'La prima frase più famosa del latino',
  description: 'The opening of the whole work, and the first Latin most students ever translate. Caesar divides Gaul into three, ranks its peoples by how far they live from a wine merchant, and quietly explains why the Belgae and the Helvetii are about to be the first two enemies of the book. The excerpt stops at section 4; sections 5 to 7 are a dry survey of river boundaries.',
  descriptionIt: 'L\'apertura dell\'intera opera, e il primo latino che quasi ogni studente traduce. Cesare divide la Gallia in tre, ordina i suoi popoli secondo quanto distano da un mercante di vino e spiega con discrezione perché i Belgi e gli Elvezi saranno i primi due nemici del libro. Il brano si ferma al paragrafo 4: i paragrafi da 5 a 7 sono un arido elenco di confini fluviali.',
  english: '> [1] **1.** Gaul as a whole is divided into three parts, one of which the Belgae inhabit, another the Aquitani, and the third those who in their own language are called Celts and in ours Gauls. **2.** All of these differ from one another in language, institutions and laws. The river Garonne separates the Gauls from the Aquitani, the Marne and the Seine from the Belgae. **3.** Of all these the bravest are the Belgae, for the reason that they are furthest away from the civilization and refinement of the Province, and traders very seldom travel to them or import the sort of thing that goes to soften the spirit; **4.** and they are nearest to the Germans who live across the Rhine, with whom they are continually at war. For this same reason the Helvetii too surpass the rest of the Gauls in valour, because they clash with the Germans in almost daily engagements, either keeping them out of their own territory or making war themselves in the territory of the Germans.',
  italian: '> [1] **1.** La Gallia nel suo insieme è divisa in tre parti, una delle quali la abitano i Belgi, un\'altra gli Aquitani, la terza quelli che nella loro lingua si chiamano Celti e nella nostra Galli. **2.** Tutti costoro differiscono fra loro per lingua, istituzioni e leggi. Il fiume Garonna separa i Galli dagli Aquitani, la Marna e la Senna dai Belgi. **3.** Di tutti questi i più valorosi sono i Belgi, per il fatto che sono i più lontani dalla civiltà e dalla raffinatezza della Provincia, e i mercanti si recano da loro molto di rado e non vi importano quelle cose che servono a infiacchire gli animi; **4.** e sono i più vicini ai Germani che abitano oltre il Reno, con i quali sono continuamente in guerra. Per questa stessa ragione anche gli Elvezi superano in valore gli altri Galli, perché si scontrano con i Germani in combattimenti quasi quotidiani, o tenendoli fuori dai propri confini o portando essi stessi la guerra nel territorio dei Germani.',
  analysis: 'Nine words in, the reader has met the tricolon that will organise the whole ethnography: *unam... aliam... tertiam*, three short cola of decreasing weight, no conjunctions. The Latin is as plain as Latin gets - present indicatives, subject-verb-object, one subordinate clause in the whole first sentence - and that plainness is exactly why Caesar sits where he does on the difficulty ladder. Nothing is hidden. Everything is asserted.\n\nWhat is asserted, though, is not a fact but a decision. Gaul was not divided into three; it held dozens of peoples with no common frontier, and Caesar is imposing a Roman administrative grid on it in the same breath in which he claims to be describing it. Note *divisa*, a participle with no agent: divided by whom?\n\nSection 3 is the passage\'s real argument, and it is a causal chain: the Belgae are bravest *because* they are furthest from the Province, *because* traders rarely reach them, *because* trade brings the things *quae ad effeminandos animos pertinent*. That last phrase is untranslatable without editorialising - literally "which tend towards the softening of spirits". It is the standard Roman anxiety that civilization unmans you, and Caesar states it as physics. Then section 4 applies the same law to the Helvetii, which is not an aside: they are the enemy of chapters 2 to 29, and Caesar has just told you they are hard.\n\n*Humanitas* here does not mean humanity in the moral sense. It means cultivation, the polish that comes with towns, wine and Greek - the same word Cicero uses as a compliment and Caesar uses, coolly, as a diagnosis.',
  analysisIt: 'Dopo nove parole il lettore ha già incontrato il tricolon che organizzerà tutta l\'etnografia: *unam... aliam... tertiam*, tre membri brevi di peso decrescente, senza congiunzioni. Il latino è quanto di più semplice esista - indicativi presenti, soggetto-verbo-oggetto, una sola subordinata in tutta la prima frase - e proprio questa semplicità spiega dove Cesare si collochi sulla scala di difficoltà. Nulla è nascosto. Tutto è affermato.\n\nCiò che viene affermato, però, non è un fatto ma una decisione. La Gallia non era divisa in tre: conteneva decine di popoli senza una frontiera comune, e Cesare le impone una griglia amministrativa romana nello stesso respiro in cui sostiene di descriverla. Si noti *divisa*, participio senza agente: divisa da chi?\n\nIl paragrafo 3 è la vera tesi del brano, ed è una catena causale: i Belgi sono i più valorosi *perché* sono i più lontani dalla Provincia, *perché* i mercanti raramente li raggiungono, *perché* il commercio porta con sé le cose *quae ad effeminandos animos pertinent*, "che tendono a infiacchire gli animi". È la classica ansia romana per cui la civiltà ti smascolinizza, e Cesare la enuncia come una legge fisica. Poi il paragrafo 4 applica la stessa legge agli Elvezi, e non è una digressione: sono il nemico dei capitoli 2-29, e Cesare ha appena detto che sono duri.\n\n*Humanitas* qui non significa umanità in senso morale. Significa cultura, la levigatezza che viene dalle città, dal vino e dal greco: la stessa parola che Cicerone usa come elogio e Cesare, freddamente, come diagnosi.'
},

{
  work: 'bg-i', key: 'bg.1.13', prefix: '[13] ',
  citation: '(De Bello Gallico I.13)',
  title: 'A Helvetian envoy reminds Caesar how this went last time',
  titleIt: 'Un ambasciatore elvetico ricorda a Cesare com\'era andata l\'altra volta',
  description: 'Caesar bridges the Saone in a day, a river the Helvetii had needed twenty days to cross, and they send envoys. The head of the embassy is Divico, who fifty years earlier had commanded the army that destroyed a Roman consul. Everything he says is in indirect discourse, which is the single hardest thing in Caesar.',
  descriptionIt: 'Cesare getta in un giorno un ponte sulla Saona, un fiume che agli Elvezi era costato venti giorni, e quelli mandano ambasciatori. A capo dell\'ambasceria c\'è Divicone, che cinquant\'anni prima aveva comandato l\'esercito che annientò un console romano. Tutto ciò che dice è in discorso indiretto, la cosa più difficile che ci sia in Cesare.',
  english: '> [13] **1.** After this engagement, so that he might be able to catch up with the remaining forces of the Helvetii, he saw to the building of a bridge over the Saone and led his army across by it. **2.** The Helvetii, alarmed by his sudden arrival, since they understood that he had done in a single day what they themselves had managed only with the greatest difficulty in twenty, namely to cross the river, sent envoys to him; the head of that embassy was Divico, who had been commander of the Helvetii in the war against Cassius. **3.** He dealt with Caesar in these terms: if the Roman people would make peace with the Helvetii, the Helvetii would go to that region and stay in it where Caesar had settled them and wished them to be; **4.** but if he persisted in pursuing them with war, he should call to mind both the old reverse of the Roman people and the ancient valour of the Helvetii. As for his having fallen unexpectedly on a single canton, at a time when those who had crossed the river could bring no help to their own people, he should not on that account credit much to his own courage or look down on them. They had learned from their fathers and forefathers to fight with valour rather than to rely on trickery and ambush. **5.** He should therefore not allow the place where they had halted to take its name from a disaster to the Roman people and the destruction of an army, or to hand such a memory down.',
  italian: '> [13] **1.** Compiuto questo scontro, per poter raggiungere le restanti forze degli Elvezi, fece costruire un ponte sulla Saona e così traghettò l\'esercito. **2.** Gli Elvezi, sconvolti dal suo arrivo improvviso, poiché capivano che egli aveva fatto in un solo giorno ciò che loro stessi avevano compiuto a stento in venti, cioè attraversare il fiume, gli mandarono ambasciatori; a capo di quell\'ambasceria fu Divicone, che era stato comandante degli Elvezi nella guerra contro Cassio. **3.** Egli trattò con Cesare in questi termini: se il popolo romano avesse fatto pace con gli Elvezi, gli Elvezi sarebbero andati e sarebbero rimasti in quella regione dove Cesare li avesse insediati e avesse voluto che stessero; **4.** se invece avesse insistito a perseguitarli con la guerra, si ricordasse sia dell\'antica sconfitta del popolo romano sia del valore di un tempo degli Elvezi. Quanto all\'aver assalito di sorpresa un solo cantone, in un momento in cui quelli che avevano attraversato il fiume non potevano portare aiuto ai propri, non attribuisse per questo troppo merito al proprio valore né li disprezzasse. Avevano imparato dai padri e dagli avi a combattere con il valore piuttosto che a far leva sull\'inganno e sulle imboscate. **5.** Non permettesse dunque che il luogo dove si erano fermati prendesse nome da una disfatta del popolo romano e dallo sterminio di un esercito, o ne tramandasse la memoria.',
  analysis: 'From *Is ita cum Caesare egit* to the end, not one finite verb of speech is repeated: the whole embassy runs on accusative-and-infinitive for the statements and on subjunctives for the commands. *Reminisceretur*, *ne tribueret*, *ne despiceret*, *ne committeret* are all jussive subjunctives standing in for imperatives that Divico actually used - "remember", "do not credit", "do not allow". Translating this well means reconstructing the direct speech in your head first and then putting it back into the third person, which is the drill Caesar exists to teach.\n\nThe threat is historically exact. *Bellum Cassianum* is 107 BC, when the Tigurini, one of the four Helvetian cantons, killed the consul Lucius Cassius Longinus and sent his army under the yoke. Divico commanded them. He is now perhaps eighty years old, standing in a Roman camp, telling a Roman proconsul to think carefully about place-names. Caesar reports it without a word of comment, which is far more effective than outrage would be: he lets the reader supply the outrage and then, in the next chapter, answers it himself.\n\nNotice too what the speech concedes by arguing. Divico spends a third of it explaining that the recent Roman success was luck and bad timing rather than Roman virtue - which is an admission that the Helvetii have just been beaten. And the sting in *dolo aut insidiis*, "trickery and ambush", is aimed straight at the bridge in section 1.',
  analysisIt: 'Da *Is ita cum Caesare egit* fino alla fine non si ripete un solo verbo finito di dire: l\'intera ambasceria corre sull\'accusativo con l\'infinito per le affermazioni e sul congiuntivo per gli ordini. *Reminisceretur*, *ne tribueret*, *ne despiceret*, *ne committeret* sono tutti congiuntivi iussivi che stanno al posto degli imperativi realmente pronunciati da Divicone: "ricorda", "non attribuire", "non permettere". Tradurre bene questo passo significa ricostruire prima il discorso diretto nella propria testa e poi riportarlo alla terza persona: è l\'esercizio per cui Cesare esiste.\n\nLa minaccia è storicamente precisa. Il *bellum Cassianum* è il 107 a.C., quando i Tigurini, uno dei quattro cantoni elvetici, uccisero il console Lucio Cassio Longino e fecero passare il suo esercito sotto il giogo. Li comandava Divicone. Ora ha forse ottant\'anni, sta in un accampamento romano e dice a un proconsole romano di riflettere bene sui toponimi. Cesare lo riferisce senza una parola di commento, il che è molto più efficace dell\'indignazione: lascia che sia il lettore a indignarsi e poi, nel capitolo successivo, risponde lui stesso.\n\nSi noti anche che cosa concede il discorso proprio argomentando. Divicone impiega un terzo delle sue parole a spiegare che il recente successo romano è stato fortuna e tempismo piuttosto che valore: il che equivale ad ammettere che gli Elvezi le hanno appena prese. E la stoccata di *dolo aut insidiis*, "inganno e imboscate", punta dritta al ponte del paragrafo 1.'
},

{
  work: 'bg-i', key: 'bg.1.29', prefix: '[29] ',
  citation: '(De Bello Gallico I.29)',
  title: 'The Helvetian census, written in Greek letters',
  titleIt: 'Il censimento elvetico, scritto in lettere greche',
  description: 'In the captured Helvetian camp the Romans find tablets listing, name by name, everyone who had left home. Caesar prints the numbers, and then prints the number of those who went back. He does not comment on the difference.',
  descriptionIt: 'Nell\'accampamento elvetico conquistato i Romani trovano tavolette che elencano, nome per nome, tutti quelli che erano partiti da casa. Cesare stampa i numeri, e poi stampa il numero di quelli che tornarono indietro. Sulla differenza non fa alcun commento.',
  english: '> [29] **1.** In the camp of the Helvetii tablets were found, drawn up in Greek letters, and brought to Caesar; in these tablets an account had been made out, name by name, of what number had left home of those who could bear arms, and likewise, separately, how many boys, old men and women. **2.** [Of all these matters] the total was: of persons of the Helvetii, 263,000; of the Tulingi, 36,000; of the Latobrigi, 14,000; of the Rauraci, 23,000; of the Boii, 32,000; of these, those who could bear arms, about 92,000. **3.** The total of them all was about 368,000. Of those who returned home, when a census had been taken as Caesar had ordered, the number was found to be 110,000.',
  italian: '> [29] **1.** Nell\'accampamento degli Elvezi furono trovate delle tavolette, redatte in lettere greche, e portate a Cesare; in quelle tavolette era stato compilato il conto, nome per nome, di quanti fossero usciti di casa fra coloro che potevano portare le armi, e parimenti, separatamente, quanti fossero i fanciulli, i vecchi e le donne. **2.** [Di tutte queste voci] il totale era: di persone degli Elvezi 263.000, dei Tulingi 36.000, dei Latobrigi 14.000, dei Rauraci 23.000, dei Boi 32.000; di questi, quanti potevano portare le armi, circa 92.000. **3.** Il totale complessivo fu di circa 368.000. Di quelli che tornarono a casa, fatto il censimento come Cesare aveva ordinato, il numero risultò essere di 110.000.',
  analysis: 'This is the plainest Latin in the batch and the hardest to read without flinching. There is not one adjective of feeling in it, not one verb of which a Roman is the emotional subject. The chapter is a document: *tabulae repertae sunt... ratio confecta erat... summa erat... repertus est numerus*. Four passives, all of them administrative.\n\nDo the arithmetic Caesar declines to do. 368,000 left; 110,000 came back. The chapter is a casualty figure written as a filing exercise, and its power is entirely in the refusal to say so. Modern historians doubt the numbers - they may be inflated, and the tablets may not have existed - but the rhetorical construction is unaffected either way, and arguably it is the construction that matters: Caesar wants the Senate to read a ledger, not a massacre.\n\nTwo details reward a second look. First, *litteris Graecis*: the Helvetii kept their records in the Greek alphabet, which is precisely what the druids do in *De Bello Gallico* VI.14 for everything except their doctrine - the two passages are worth reading together. Second, the manuscripts write *milia nonaginta duo* out in words while every other figure here is a numeral, a small inconsistency that the Latin Library preserves.\n\n**[Quarum omnium rerum]** stands in square brackets because it is an editorial supplement: the phrase is not securely transmitted, and editors add it to hold the sentence together. The app prints it as the source does rather than silently absorbing it.',
  analysisIt: 'È il latino più semplice del gruppo e il più difficile da leggere senza trasalire. Non c\'è un solo aggettivo affettivo, non un solo verbo di cui un Romano sia il soggetto emotivo. Il capitolo è un documento: *tabulae repertae sunt... ratio confecta erat... summa erat... repertus est numerus*. Quattro passivi, tutti amministrativi.\n\nSi faccia il conto che Cesare si rifiuta di fare. Partirono in 368.000; ne tornarono 110.000. Il capitolo è un bilancio di perdite scritto come una pratica d\'ufficio, e la sua forza sta tutta nel rifiuto di dirlo. Gli storici moderni dubitano delle cifre - potrebbero essere gonfiate, e le tavolette potrebbero non essere mai esistite - ma la costruzione retorica non cambia, ed è forse la costruzione a contare: Cesare vuole che il Senato legga un registro, non un massacro.\n\nDue dettagli meritano un secondo sguardo. Primo, *litteris Graecis*: gli Elvezi tenevano i loro registri in alfabeto greco, esattamente come fanno i druidi nel *De Bello Gallico* VI.14 per tutto tranne che per la loro dottrina; i due passi vanno letti insieme. Secondo, i manoscritti scrivono *milia nonaginta duo* per esteso mentre ogni altra cifra qui è in numeri, una piccola incoerenza che The Latin Library conserva.\n\n**[Quarum omnium rerum]** sta fra parentesi quadre perché è un\'integrazione editoriale: l\'espressione non è tramandata con sicurezza e gli editori la aggiungono per tenere insieme la frase. L\'app la stampa come fa la fonte, invece di assorbirla in silenzio.'
},

{
  work: 'bg-i', key: 'bg.1.39', prefix: '[39] ',
  citation: '(De Bello Gallico I.39)',
  title: 'The whole army starts writing its will',
  titleIt: 'Tutto l\'esercito comincia a fare testamento',
  description: 'Halted at Vesontio before the march against Ariovistus, the army listens to what the locals have to say about Germans and falls apart. The panic starts at the top, among the young gentlemen who came out from Rome for the company, and works its way down to the centurions.',
  descriptionIt: 'Fermo a Vesontio prima della marcia contro Ariovisto, l\'esercito ascolta ciò che i locali hanno da dire sui Germani e va in pezzi. Il panico comincia dall\'alto, fra i giovani signori venuti da Roma per fare compagnia, e scende fino ai centurioni.',
  english: '> [39] **1.** While he lingered a few days at Vesontio for the sake of grain and supplies, from the questioning of our own men and from the talk of the Gauls and the traders -- who kept proclaiming that the Germans were of enormous bodily size, of incredible courage and training in arms (they said that many a time, when they had met them, they had not been able to bear even their expression and the glare of their eyes) -- so great a fear suddenly seized the whole army that it threw everyone\'s minds and spirits into no small disorder. **2.** It arose first among the military tribunes, the prefects and the rest who had followed Caesar from the city for friendship\'s sake and had no great experience in military matters: **3.** of these, one alleging one reason and another another, which he would say was necessary for his departure, kept asking to be allowed to leave with Caesar\'s consent; some, moved by shame, stayed, in order to avoid the suspicion of fear. **4.** These could neither compose their faces nor at times hold back their tears: shut away in their tents they either bewailed their own fate or lamented the common danger with their friends. Everywhere throughout the camp wills were being sealed. **5.** By their words and their fear even those who had long experience of camp -- soldiers, centurions and the commanders of the cavalry -- were gradually unsettled. **6.** Those of them who wanted to be thought less frightened said that they were not afraid of the enemy, but of the narrowness of the route and the size of the forests lying between themselves and Ariovistus, or of the grain supply, whether it could be brought up conveniently enough. **7.** Some even reported to Caesar that when he had given the order to strike camp and advance the standards, the soldiers would not obey the word of command and would not carry the standards forward, out of fear.',
  italian: '> [39] **1.** Mentre indugiava per qualche giorno a Vesontio per il grano e i rifornimenti, dalle domande poste dai nostri e dalle voci dei Galli e dei mercanti -- i quali andavano proclamando che i Germani erano di enorme statura, di incredibile valore e addestramento nelle armi (dicevano che molte volte, essendosi scontrati con loro, non erano riusciti a sostenerne neppure lo sguardo e il lampo degli occhi) -- una paura così grande si impadronì all\'improvviso di tutto l\'esercito da sconvolgere non poco le menti e gli animi di tutti. **2.** Nacque dapprima fra i tribuni militari, i prefetti e gli altri che avevano seguito Cesare da Roma per amicizia e non avevano grande esperienza militare: **3.** di questi, chi adduceva un pretesto e chi un altro, che diceva essergli necessario per partire, chiedeva di potersene andare con il consenso di lui; alcuni, trattenuti dalla vergogna, restavano, per evitare il sospetto di paura. **4.** Costoro non riuscivano né a comporre il volto né, a tratti, a trattenere le lacrime: nascosti nelle tende, o si lamentavano della propria sorte o compiangevano con gli amici il pericolo comune. Dappertutto, per tutto l\'accampamento, si sigillavano testamenti. **5.** Per le loro parole e la loro paura, a poco a poco, anche quelli che avevano lunga esperienza di accampamento -- soldati, centurioni e comandanti della cavalleria -- si turbavano. **6.** Quelli fra loro che volevano essere ritenuti meno paurosi dicevano di non temere il nemico, ma le strettoie del percorso e l\'estensione delle foreste che si frapponevano fra loro e Ariovisto, oppure il rifornimento di grano, se potesse essere portato con sufficiente comodità. **7.** Alcuni riferivano perfino a Cesare che, quando avesse dato ordine di levare il campo e di far avanzare le insegne, i soldati non avrebbero obbedito al comando e non avrebbero portato avanti le insegne, per paura.',
  analysis: 'The best piece of psychology in the commentarii, and it is built out of grammar. Section 1 is a single enormous period whose main clause - *tantus subito timor omnem exercitum occupavit* - does not arrive until the reader has waded through the questioning, the traders, and a parenthesis inside the parenthesis. The fear reaches you in the same order it reached the camp: rumour first, then the thing itself.\n\nThe direction of the panic is the point. It starts with the *tribuni militum* and the *praefecti* and the young men who came out *amicitiae causa* - senators\' sons on a season abroad, with *non magnum in re militari usum* - and only then infects the professionals. Caesar is settling a private score in public, and doing it without a single word of abuse.\n\nThen the sentence that everything else exists for: *Vulgo totis castris testamenta obsignabantur*. Six words, one imperfect passive, no subject worth naming. It sits alone between two longer sentences and Caesar adds nothing to it.\n\nSection 6 is where the style turns quietly savage. Watch the mood change: as soon as men start making excuses, the narrative slides into indirect discourse - *non se hostem vereri, sed angustias... timere dicebant*. Caesar is quoting them, and quotation is the cruellest thing he can do, because it lets the excuse convict itself. Those two excuses, the roads and the grain, are the ones he demolishes by name in the next chapter.',
  analysisIt: 'È il miglior pezzo di psicologia dei commentari, ed è costruito con la grammatica. Il paragrafo 1 è un unico periodo enorme la cui principale - *tantus subito timor omnem exercitum occupavit* - non arriva finché il lettore non ha attraversato le domande, i mercanti e una parentesi dentro la parentesi. La paura raggiunge il lettore nello stesso ordine in cui raggiunse l\'accampamento: prima la diceria, poi la cosa.\n\nLa direzione del panico è il punto. Comincia dai *tribuni militum*, dai *praefecti* e dai giovani venuti *amicitiae causa* - figli di senatori in trasferta, con *non magnum in re militari usum* - e solo dopo contagia i professionisti. Cesare sta regolando in pubblico un conto privato, e lo fa senza una sola parola di insulto.\n\nPoi la frase per cui tutto il resto esiste: *Vulgo totis castris testamenta obsignabantur*. Sei parole, un imperfetto passivo, nessun soggetto degno di essere nominato. Sta da sola fra due frasi più lunghe e Cesare non vi aggiunge nulla.\n\nIl paragrafo 6 è il punto in cui lo stile diventa sommessamente feroce. Si osservi il cambio di modo: appena gli uomini cominciano a cercare scuse, la narrazione scivola nel discorso indiretto - *non se hostem vereri, sed angustias... timere dicebant*. Cesare li sta citando, e la citazione è la cosa più crudele che possa fare, perché lascia che la scusa si condanni da sola. Quelle due scuse, le strade e il grano, sono quelle che smonterà per nome nel capitolo successivo.'
},

{
  work: 'bg-i', key: 'bg.1.40', prefix: '[40] ',
  citation: '(De Bello Gallico I.40)',
  title: 'Then I will go with the Tenth alone',
  titleIt: 'Allora andrò con la sola Decima',
  description: 'Caesar\'s answer to the panic of the previous chapter. This is the last third of a very long speech - the subsection numbers start at 10 - where he stops arguing about Germans and starts talking about his officers, and it ends with the most famous vote of confidence in Roman military history.',
  descriptionIt: 'La risposta di Cesare al panico del capitolo precedente. È l\'ultimo terzo di un discorso lunghissimo - i numeri di paragrafo partono da 10 - in cui smette di discutere di Germani e comincia a parlare dei suoi ufficiali, e si chiude con il più celebre attestato di fiducia della storia militare romana.',
  emend: [['de quarta, vigilia', 'de quarta vigilia']],
  english: '> [40] **10.** As for those who were transferring their own fear onto a pretence about the grain supply and the narrowness of the route, they were behaving arrogantly, since they appeared either to despair of their commander\'s sense of duty or to give him instructions. **11.** These matters were his concern: the Sequani, the Leuci and the Lingones were supplying grain, and the corn in the fields was already ripe; as for the route, they would judge it for themselves before long. **12.** As for the report that they would not obey the word of command and would not carry the standards forward, that did not trouble him in the least: he knew that with any general whose army had not obeyed him, either luck had failed after a campaign was bungled, or greed had been convicted after some crime had come to light. **13.** His own integrity had been made plain by his whole life, his good fortune by the Helvetian war. **14.** He would therefore bring forward what he had been going to put off to a later day, and would strike camp the following night at the fourth watch, so that he might learn as soon as possible whether shame and duty counted for more with them than fear. **15.** And if no one else were to follow, even so he would go with the Tenth Legion alone, of which he had no doubt, and it would be his praetorian cohort. Caesar had particularly indulged this legion and, on account of its valour, trusted it most of all.',
  italian: '> [40] **10.** Quanto a quelli che trasferivano la propria paura su un pretesto riguardante il rifornimento di grano e le strettoie del percorso, si comportavano con arroganza, poiché sembravano o disperare del senso del dovere del loro comandante o dargli istruzioni. **11.** Di queste cose si stava occupando lui: i Sequani, i Leuci e i Lingoni fornivano il grano, e il frumento nei campi era già maturo; quanto al percorso, lo avrebbero giudicato da soli fra poco. **12.** Quanto alla voce che non avrebbero obbedito al comando e non avrebbero portato avanti le insegne, la cosa non lo turbava minimamente: sapeva infatti che, con qualunque comandante un esercito non avesse obbedito, o era mancata la fortuna dopo una campagna condotta male, o era stata provata l\'avidità dopo la scoperta di qualche misfatto. **13.** La propria integrità era stata dimostrata da tutta la sua vita, la propria fortuna dalla guerra elvetica. **14.** Avrebbe perciò anticipato ciò che aveva intenzione di rimandare a un giorno più lontano, e avrebbe levato il campo la notte seguente alla quarta vigilia, per poter capire il prima possibile se presso di loro valessero di più la vergogna e il dovere o la paura. **15.** E se nessun altro lo avesse seguito, sarebbe andato ugualmente con la sola Decima legione, della quale non dubitava, e quella sarebbe stata la sua coorte pretoria. Cesare aveva favorito in modo particolare questa legione e, per il suo valore, si fidava di essa più di ogni altra.',
  analysis: 'The whole speech is in indirect discourse, which produces one of the strangest effects in Latin prose: Caesar is reporting his own words as though someone else were reporting them. *Suam innocentiam perpetua vita... esse perspectam* is, in the third person, a statement of fact about a man called Caesar. Put it back into the first person and it is an enormous boast. The grammar launders it.\n\nSection 12 is a small masterpiece of cold logic. Told that his men may mutiny, Caesar does not threaten them; he offers a dilemma. Armies only disobey generals who are unlucky or corrupt. He is neither, and section 13 supplies the evidence for both halves in a single balanced clause - *innocentiam... vita, felicitatem... bello* - with the verb saved for the end and *perspectam* covering both.\n\n*Repraesentaturum* in section 14 is a word from banking: to *repraesentare* a payment is to settle it now instead of on the due date. Caesar applies it to a war. And moving at the *quarta vigilia*, the last watch before dawn, is not a detail but the test itself - he is giving the army the shortest possible interval in which to decide.\n\nThen the ending. *Sibique eam praetoriam cohortem futuram* offers the Tenth the standing of the general\'s own bodyguard, and it worked: the Tenth is his favourite legion for the rest of the war. Suetonius reports that on a later occasion Caesar quelled mutinous troops by addressing them as *Quirites*, "citizens", instead of as soldiers, and they begged to be taken back. He had learned here what that particular button does.\n\n**Textual note:** the Latin Library prints *de quarta, vigilia castra moturum* with a stray comma inside the phrase; the app prints *de quarta vigilia*, which is what the words mean and what every edition gives. The reading itself is not in doubt, only the pointing.',
  analysisIt: 'Tutto il discorso è in discorso indiretto, il che produce uno degli effetti più strani della prosa latina: Cesare riferisce le proprie parole come se le riferisse un altro. *Suam innocentiam perpetua vita... esse perspectam* è, in terza persona, la constatazione di un fatto su un uomo di nome Cesare. Lo si riporti alla prima persona ed è un vanto enorme. La grammatica lo ripulisce.\n\nIl paragrafo 12 è un piccolo capolavoro di logica fredda. Avvisato che i suoi potrebbero ammutinarsi, Cesare non minaccia: propone un dilemma. Gli eserciti disobbediscono solo ai comandanti sfortunati o corrotti. Lui non è né l\'uno né l\'altro, e il paragrafo 13 fornisce la prova di entrambe le metà in un\'unica clausola bilanciata - *innocentiam... vita, felicitatem... bello* - con il verbo tenuto per la fine e *perspectam* che copre tutte e due.\n\n*Repraesentaturum* al paragrafo 14 è un termine bancario: *repraesentare* un pagamento significa saldarlo subito invece che alla scadenza. Cesare lo applica a una guerra. E muoversi alla *quarta vigilia*, l\'ultimo turno di guardia prima dell\'alba, non è un dettaglio ma la prova stessa: sta concedendo all\'esercito il minimo intervallo possibile per decidere.\n\nPoi il finale. *Sibique eam praetoriam cohortem futuram* offre alla Decima il rango di guardia personale del comandante, e funzionò: la Decima resta la sua legione prediletta per tutta la guerra. Svetonio racconta che in un\'occasione successiva Cesare sedò dei soldati ammutinati chiamandoli *Quirites*, "cittadini", invece che commilitoni, e quelli lo supplicarono di riprenderli. Qui aveva imparato che cosa fa quel particolare bottone.\n\n**Nota testuale:** The Latin Library stampa *de quarta, vigilia castra moturum* con una virgola vagante dentro l\'espressione; l\'app stampa *de quarta vigilia*, che è ciò che le parole significano e ciò che danno tutte le edizioni. In dubbio non è la lezione, ma solo la punteggiatura.'
},

{
  work: 'bg-i', key: 'bg.1.53', prefix: '[53] ',
  citation: '(De Bello Gallico I.53)',
  title: 'Three times they cast lots over the man in chains',
  titleIt: 'Per tre volte tirarono a sorte sull\'uomo in catene',
  description: 'The end of the Ariovistus campaign. Caesar gives the rout, the escape of the German king and the death of his two wives and one of his daughters in a few clauses, and then spends four times as long on a single friend recovered from the fleeing column.',
  descriptionIt: 'La fine della campagna contro Ariovisto. Cesare liquida la rotta, la fuga del re germanico e la morte delle sue due mogli e di una delle figlie in poche proposizioni, e poi dedica quattro volte tanto spazio a un solo amico recuperato dalla colonna in fuga.',
  english: '> [53] **1.** So the battle was restored, and all the enemy turned their backs and did not stop fleeing until they reached the river Rhine, about fifty miles from that place. **2.** There a very few, trusting to their strength, struggled to swim across, or found boats and so found safety. **3.** Among these was Ariovistus, who came upon a small boat moored at the bank and escaped in it; all the rest our cavalry caught up with and killed. **4.** Ariovistus had two wives, one a Sueban by birth, whom he had brought with him from home, the other from Noricum, the sister of king Voccio, whom he had married in Gaul after her brother sent her: both perished in that flight. There were two daughters: one of them was killed, the other captured. **5.** Gaius Valerius Procillus, as he was being dragged along by his guards in the rout, bound with three chains, fell in with Caesar himself as he pursued with the cavalry. **6.** This in fact gave Caesar no less pleasure than the victory itself, because he saw a most honourable man of the province of Gaul, his own friend and guest, snatched from the enemy\'s hands and given back to him, and fortune had taken nothing from so great a pleasure and rejoicing by any misfortune of his. **7.** He said that in his own presence the lots had been consulted about him three times, whether he should be burned to death at once or kept for another time: by the kindness of the lots he was unharmed.',
  italian: '> [53] **1.** Così la battaglia fu ristabilita, e tutti i nemici voltarono le spalle e non smisero di fuggire finché non giunsero al fiume Reno, a circa cinquanta miglia da quel luogo. **2.** Lì pochissimi, fidando nelle proprie forze, tentarono di passare a nuoto, oppure trovarono delle barche e così trovarono salvezza. **3.** Fra questi ci fu Ariovisto, che trovò una barchetta ormeggiata alla riva e fuggì con quella; tutti gli altri i nostri cavalieri li raggiunsero e li uccisero. **4.** Ariovisto aveva due mogli, una di stirpe sueba, che si era portata da casa, l\'altra norica, sorella del re Voccione, che aveva sposato in Gallia dopo che il fratello gliela aveva mandata: entrambe perirono in quella fuga. Le figlie erano due: una fu uccisa, l\'altra catturata. **5.** Gaio Valerio Procillo, mentre veniva trascinato dalle guardie durante la fuga, legato con tre catene, si imbatté in Cesare in persona che inseguiva con la cavalleria. **6.** La cosa procurò a Cesare un piacere non minore della vittoria stessa, perché vedeva un uomo onoratissimo della provincia di Gallia, suo amico e ospite, strappato alle mani dei nemici e restituito a lui, e la fortuna non aveva tolto nulla a un piacere e a una gioia così grandi con alcuna disgrazia di lui. **7.** Raccontava che in sua presenza erano state consultate per tre volte le sorti sul suo conto, se dovesse essere bruciato vivo subito o riservato a un altro momento: per grazia delle sorti era incolume.',
  analysis: 'Read this chapter for its proportions. Two wives and a daughter are killed in eleven Latin words, in a subordinate clause, with no verb of grief anywhere near them. Then one man in chains gets three full sections, a superlative, a relative clause of appreciation and a closing anecdote. That is not carelessness; it is the moral arithmetic of a Roman aristocrat set down without apology, and it tells you more about Caesar than any speech in the book.\n\n*Hominem honestissimum provinciae Galliae, suum familiarem et hospitem*: Procillus is a Gaul. He is also Caesar\'s guest-friend, bound by *hospitium*, the oldest reciprocal obligation in Roman social life. The phrase contains the entire Caesarian policy in Gaul - conquest carried out through personal ties with provincial notables - and it explains why the rescue registers as a private joy rather than a strategic one.\n\nSection 7 is the strangest thing in the chapter and the most valuable to a historian. The Germans decided Procillus\'s fate by drawing lots, three times, in front of him. Tacitus describes exactly this practice in the *Germania*, a century and a half later, as the standard Germanic method of divination; Caesar\'s sentence is the earliest Roman evidence for it, and it arrives inside an adventure story rather than an ethnographic digression.\n\nThe excerpt stops at the end of section 7. Section 8 is a single line recording that another envoy, Marcus Metius, was also found - and putting it back would blunt the ending, which is *sortium beneficio se esse incolumem*: he was alive by the kindness of the dice.',
  analysisIt: 'Questo capitolo va letto per le sue proporzioni. Due mogli e una figlia vengono uccise in undici parole latine, in una subordinata, senza un verbo di dolore nelle vicinanze. Poi un solo uomo in catene ottiene tre interi paragrafi, un superlativo, una relativa di apprezzamento e un aneddoto conclusivo. Non è distrazione: è l\'aritmetica morale di un aristocratico romano messa per iscritto senza scuse, e dice di Cesare più di qualunque discorso del libro.\n\n*Hominem honestissimum provinciae Galliae, suum familiarem et hospitem*: Procillo è un Gallo. Ed è anche ospite di Cesare, legato a lui dall\'*hospitium*, il più antico vincolo reciproco della vita sociale romana. L\'espressione contiene tutta la politica cesariana in Gallia - una conquista condotta attraverso legami personali con i notabili provinciali - e spiega perché il salvataggio si registri come una gioia privata e non come un vantaggio strategico.\n\nIl paragrafo 7 è la cosa più strana del capitolo e la più preziosa per uno storico. I Germani decisero la sorte di Procillo tirando a sorte, tre volte, davanti a lui. Tacito descrive esattamente questa pratica nella *Germania*, un secolo e mezzo dopo, come il metodo divinatorio germanico per eccellenza; la frase di Cesare è la più antica testimonianza romana in proposito, e arriva dentro un racconto d\'avventura invece che in una digressione etnografica.\n\nIl brano si ferma alla fine del paragrafo 7. Il paragrafo 8 è una riga sola che registra il ritrovamento di un altro ambasciatore, Marco Metio: rimetterlo smorzerebbe la chiusa, che è *sortium beneficio se esse incolumem*, era vivo per grazia dei dadi.'
}

];
