/*
 * v1.11.1 - De Bello Gallico, Book II (4). Same rules as frags1111a.js: the
 * Latin comes from batch/passages1111.json, never from the keyboard. Two of
 * these span two chapters, so their translations carry the inner chapter marker
 * and restart the subsection count, exactly as the Latin does.
 */
module.exports = [

{
  work: 'bg-ii', key: 'bg.2.1', prefix: '[1] ',
  citation: '(De Bello Gallico II.1)',
  title: 'Four reasons a province revolts',
  titleIt: 'Quattro motivi per cui una provincia si ribella',
  description: 'Book II opens with Caesar still in winter quarters and a letter arriving from Labienus. Before a soldier moves, he sets out the causes of the Belgic conspiracy in four ranked clauses - the closest thing to political analysis anywhere in the commentarii, and the last one is an admission.',
  descriptionIt: 'Il libro II si apre con Cesare ancora nei quartieri invernali e una lettera in arrivo da Labieno. Prima che un soldato si muova, egli espone le cause della congiura belgica in quattro proposizioni ordinate: la cosa più simile a un\'analisi politica che ci sia nei commentari, e l\'ultima è un\'ammissione.',
  english: '> [1] **1.** While Caesar was in Nearer Gaul [in winter quarters], as we showed above, repeated rumours were being brought to him, and he was also informed by a letter from Labienus, that all the Belgae -- who, as we said, are a third part of Gaul -- were conspiring against the Roman people and exchanging hostages among themselves. **2.** The reasons for conspiring were these: first, that they were afraid that once the whole of Gaul was pacified our army would be brought against them; **3.** second, that they were being stirred up by a number of Gauls -- partly by those who, just as they had not wanted the Germans to stay any longer in Gaul, so resented an army of the Roman people wintering in Gaul and settling in for good, and partly by those who out of fickleness and lightness of mind were eager for a change of ruler; **4.** and by some also because in Gaul kingdoms were commonly seized by the more powerful and by those who had the means to hire men, and these found it less easy to bring that off under our rule.',
  italian: '> [1] **1.** Mentre Cesare si trovava nella Gallia Citeriore [nei quartieri invernali], come abbiamo mostrato sopra, gli giungevano voci insistenti, ed era informato anche da una lettera di Labieno, che tutti i Belgi -- i quali, come abbiamo detto, sono una terza parte della Gallia -- congiuravano contro il popolo romano e si scambiavano ostaggi fra loro. **2.** I motivi della congiura erano questi: primo, che temevano che, pacificata tutta la Gallia, il nostro esercito venisse condotto contro di loro; **3.** secondo, che venivano istigati da un certo numero di Galli, in parte da quelli che, come non avevano voluto che i Germani si trattenessero più a lungo in Gallia, così mal sopportavano che un esercito del popolo romano svernasse in Gallia e vi mettesse radici, in parte da quelli che per volubilità e leggerezza d\'animo desideravano un cambio di padrone; **4.** e da alcuni anche perché in Gallia i regni venivano comunemente occupati dai più potenti e da quanti avevano i mezzi per assoldare uomini, e costoro con il nostro dominio riuscivano meno facilmente a portare a termine quel disegno.',
  analysis: 'The whole chapter is one long stretch of indirect statement hanging off *certior fiebat*, "he was being informed" - so every clause in it is what Labienus and the rumours said, not what Caesar asserts. That is worth noticing before you decide how much to trust the analysis that follows.\n\nAnd it is an analysis. *Primum... deinde... ab non nullis etiam*: three ranked causes, with the third splitting into two, which gives four in all. They descend from the respectable to the cynical. Fear of Rome is a reason a Roman reader can accept. Resentment at an army that *hiemare atque inveterascere in Gallia* - wintering and, literally, "growing old" there - is the sharpest phrase in the chapter, because it says out loud what everyone knew: the legions were not leaving. *Mobilitate et levitate animi* is stock ethnographic contempt, the standard Roman charge against Gauls, and it costs Caesar nothing to make.\n\nThe fourth cause is the one that repays reading twice. Gallic nobles used to buy their way to kingship by hiring armed retainers; under Roman rule they cannot. Caesar puts this among the reasons for a *conspiracy against the Roman people*, and in doing so concedes that Roman government is an obstacle to Gallic ambition - which is precisely what the rebels will say for the next six books.\n\n**[in hibernis]** is in square brackets because editors add it: the phrase is not securely transmitted. The app prints the source\'s brackets rather than quietly absorbing the words.',
  analysisIt: 'L\'intero capitolo è un unico lungo tratto di discorso indiretto retto da *certior fiebat*, "veniva informato": ogni proposizione, dunque, è ciò che dicevano Labieno e le voci, non ciò che afferma Cesare. Vale la pena accorgersene prima di decidere quanto fidarsi dell\'analisi che segue.\n\nEd è un\'analisi. *Primum... deinde... ab non nullis etiam*: tre cause ordinate, con la terza che si sdoppia, e quindi quattro in tutto. Scendono dal rispettabile al cinico. La paura di Roma è un motivo che un lettore romano può accettare. Il risentimento verso un esercito che *hiemare atque inveterascere in Gallia*, che sverna e letteralmente "invecchia" in Gallia, è l\'espressione più tagliente del capitolo, perché dice ad alta voce ciò che tutti sapevano: le legioni non se ne sarebbero andate. *Mobilitate et levitate animi* è disprezzo etnografico di repertorio, l\'accusa standard dei Romani ai Galli, e a Cesare non costa nulla.\n\nLa quarta causa è quella che merita una seconda lettura. I nobili galli si compravano la regalità assoldando seguaci armati; sotto il dominio romano non possono più. Cesare la mette fra i motivi di una *congiura contro il popolo romano*, e così facendo ammette che il governo romano è un ostacolo all\'ambizione gallica: esattamente ciò che i ribelli diranno per i sei libri successivi.\n\n**[in hibernis]** è fra parentesi quadre perché lo aggiungono gli editori: l\'espressione non è tramandata con sicurezza. L\'app stampa le parentesi della fonte invece di assorbire in silenzio quelle parole.'
},

{
  work: 'bg-ii', key: 'bg.2.20', prefix: '[20] ',
  citation: '(De Bello Gallico II.20-21)',
  title: 'Everything had to be done at the same moment',
  titleIt: 'Tutto andava fatto nello stesso momento',
  description: 'The Nervii charge while the legions are still digging their camp. Caesar writes the general\'s to-do list as seven gerundives in a row, then admits there was no time to do most of it - and explains, without embarrassment, that the army handled it without him.',
  descriptionIt: 'I Nervi caricano mentre le legioni stanno ancora scavando l\'accampamento. Cesare scrive la lista di cose da fare del comandante come sette gerundivi di seguito, poi ammette che non ci fu tempo per farne la maggior parte, e spiega senza imbarazzo che l\'esercito se la cavò senza di lui.',
  english: '> [20] **1.** Caesar had everything to do at one and the same moment: the flag had to be displayed, which was the signal for running to arms; the trumpet call had to be sounded; the soldiers had to be called back from their work; those who had gone rather far off to fetch material for the rampart had to be summoned; the line had to be drawn up; the men had to be encouraged; the signal had to be given. **2.** A large part of these things the shortness of the time and the enemy\'s charge prevented. **3.** Against these difficulties two things were a help: the knowledge and experience of the soldiers, since, trained by earlier battles, they could prescribe for themselves what needed doing quite as well as they could be told by others; and the fact that Caesar had forbidden the individual generals to leave their individual legions and the works until the camp was fortified. **4.** These men, because of the enemy\'s nearness and speed, no longer waited for any order from Caesar, but managed on their own whatever seemed right.\n>\n> [21] **1.** Caesar, having given the orders that had to be given, ran down to encourage the soldiers in whatever direction chance offered, and came to the Tenth Legion. **2.** He encouraged the men with a speech no longer than that they should keep the memory of their old valour, and not be shaken in spirit, and withstand the enemy\'s charge bravely; **3.** and because the enemy were no further off than a spear could be thrown, he gave the signal for joining battle. **4.** And setting out to the other side, likewise to encourage them, he ran into men already fighting. **5.** So short was the time and so ready the enemy\'s spirit for the fight that there was no time not only for putting on decorations but even for putting on helmets and stripping the covers off shields. **6.** Whatever part each man happened to reach from the work, and whatever standards he first caught sight of, at these he took his stand, so as not to waste fighting time in looking for his own unit.',
  italian: '> [20] **1.** Cesare doveva fare tutto in uno stesso momento: bisognava esporre il vessillo, che era il segnale per correre alle armi; bisognava dare il segnale con la tromba; bisognava richiamare i soldati dai lavori; bisognava far tornare quelli che si erano spinti un po\' più lontano a procurare materiale per il terrapieno; bisognava schierare l\'esercito; bisognava esortare gli uomini; bisognava dare il segnale. **2.** Gran parte di queste cose la brevità del tempo e l\'assalto dei nemici le impedivano. **3.** In queste difficoltà due cose furono d\'aiuto: la competenza e l\'esperienza dei soldati, poiché, addestrati dalle battaglie precedenti, sapevano prescriversi da sé che cosa fare non meno bene di quanto potessero farselo insegnare da altri; e il fatto che Cesare avesse vietato ai singoli legati di allontanarsi dalle singole legioni e dai lavori prima che l\'accampamento fosse fortificato. **4.** Costoro, per la vicinanza e la rapidità dei nemici, non attendevano ormai più alcun ordine di Cesare, ma provvedevano da soli a quanto sembrava opportuno.\n>\n> [21] **1.** Cesare, impartiti gli ordini necessari, corse giù a esortare i soldati nella direzione che il caso gli offrì, e giunse alla Decima legione. **2.** Esortò gli uomini con un discorso non più lungo di questo: che conservassero il ricordo del loro antico valore, che non si lasciassero turbare nell\'animo e che sostenessero con coraggio l\'assalto dei nemici; **3.** e poiché i nemici non erano più lontani di quanto si potesse lanciare un giavellotto, diede il segnale di attaccare battaglia. **4.** E partito dall\'altra parte, ugualmente per esortare, si imbatté in uomini che già combattevano. **5.** Tanto breve fu il tempo e tanto pronto l\'animo dei nemici alla battaglia che mancò il tempo non solo per mettersi le decorazioni, ma perfino per infilarsi gli elmi e togliere le fodere dagli scudi. **6.** Ciascuno si fermò nella parte in cui il caso lo aveva portato venendo dai lavori e presso le prime insegne che aveva scorto, per non perdere tempo di combattimento cercando il proprio reparto.',
  analysis: 'Seven gerundives in a row, in asyndeton: *proponendum, dandum, revocandi, arcessendi, instruenda, cohortandi, dandum*. The passive periphrastic states an obligation without saying who is to meet it or when, so the list arrives as pure pressure - seven things that must happen, all of them at once, none of them yet begun. It is one of the most imitated sentences in Latin prose, and it works because Caesar does not add a single word of comment.\n\nThen section 2 pulls the rug: most of it could not be done. And section 3, instead of rescuing the general\'s reputation, hands the credit to the men - *scientia atque usus militum* - and to a standing order given weeks earlier. The point is not modesty. It is Caesar\'s central claim about his army: it is a machine that runs without him, and building it was the achievement.\n\n*Quam in partem fors obtulit* is the most honest phrase in the chapter. Not "where he judged the danger greatest" but "in whatever direction chance offered". Compare the Tenth Legion turning up here, in the place Caesar happens to reach first, having been promised in *De Bello Gallico* I.40 that it would be his praetorian cohort.\n\nSection 21.5 is the detail that proves the eyewitness: no time to put on helmets or take the leather covers off the shields. Nobody who had not been there would think to say it.',
  analysisIt: 'Sette gerundivi di fila, in asindeto: *proponendum, dandum, revocandi, arcessendi, instruenda, cohortandi, dandum*. La perifrastica passiva enuncia un obbligo senza dire chi debba assolverlo né quando, e così l\'elenco arriva come pura pressione: sette cose che devono accadere, tutte insieme, nessuna ancora cominciata. È una delle frasi più imitate della prosa latina, e funziona perché Cesare non vi aggiunge una sola parola di commento.\n\nPoi il paragrafo 2 toglie il tappeto da sotto i piedi: gran parte di quelle cose non si poté fare. E il paragrafo 3, invece di salvare la reputazione del comandante, attribuisce il merito agli uomini - *scientia atque usus militum* - e a un ordine permanente dato settimane prima. Non è modestia. È la tesi centrale di Cesare sul proprio esercito: è una macchina che funziona senza di lui, e averla costruita è l\'impresa.\n\n*Quam in partem fors obtulit* è l\'espressione più onesta del capitolo. Non "dove giudicò maggiore il pericolo", ma "nella direzione che il caso gli offrì". Si confronti la Decima legione che compare qui, nel punto in cui Cesare arriva per primo, dopo che nel *De Bello Gallico* I.40 le era stato promesso che sarebbe stata la sua coorte pretoria.\n\nIl paragrafo 21.5 è il dettaglio che dimostra il testimone oculare: non c\'è tempo per mettersi gli elmi né per togliere le fodere di cuoio dagli scudi. Chi non fosse stato lì non penserebbe a dirlo.'
},

{
  work: 'bg-ii', key: 'bg.2.25', prefix: '[25] ',
  citation: '(De Bello Gallico II.25)',
  title: 'Caesar takes a shield off a man in the back rank',
  titleIt: 'Cesare prende lo scudo a un uomo delle ultime file',
  description: 'The Twelfth Legion is being destroyed: every centurion of the fourth cohort dead, the standard lost, the chief centurion too badly wounded to stand. The whole catastrophe arrives in a single sentence, and the main verb - *he saw* - is held back until the end of it.',
  descriptionIt: 'La Dodicesima legione sta per essere annientata: tutti i centurioni della quarta coorte morti, l\'insegna perduta, il primipilo troppo malridotto per reggersi in piedi. L\'intera catastrofe arriva in un\'unica frase, e il verbo principale - *vide* - viene trattenuto fino alla fine.',
  english: '> [25] **1.** Caesar, having gone from encouraging the Tenth Legion to the right wing, saw that his men were hard pressed and that the soldiers of the Twelfth Legion, with the standards gathered into one place, were so tightly packed that they were an obstacle to their own fighting; that all the centurions of the fourth cohort had been killed and the standard-bearer slain, the standard lost; that of the remaining cohorts almost all the centurions had been wounded or killed, among them the chief centurion Publius Sextius Baculus, a very brave man, so worn out with many severe wounds that he could no longer hold himself up; that the rest were slowing, and that some in the rearmost ranks were abandoning their post and quitting the fight and dodging the missiles; that the enemy, coming up from lower ground in front, were not letting up, and were pressing on both flanks, and that matters were critical, and that there was no reserve which could be sent up. **2.** So, taking a shield from one of the men in the rear rank, since he had come there without one himself, he advanced into the front line, and calling the centurions by name and encouraging the rest of the soldiers he ordered them to carry the standards forward and to open out the maniples, so that they could use their swords more easily. **3.** His arrival brought hope to the soldiers and restored their spirit, and since every man for his own part wanted to do his utmost in the sight of his commander, even in his own last extremity, the enemy\'s charge was checked a little.',
  italian: '> [25] **1.** Cesare, passato dall\'esortazione alla Decima legione all\'ala destra, vide che i suoi erano incalzati e che i soldati della Dodicesima legione, con le insegne raccolte in un solo punto, erano talmente ammassati da essere d\'impedimento a se stessi nel combattere; che tutti i centurioni della quarta coorte erano stati uccisi e il portainsegne ammazzato, l\'insegna perduta; che delle restanti coorti quasi tutti i centurioni erano feriti o morti, e fra loro il primipilo Publio Sestio Baculo, uomo fortissimo, stremato da molte e gravi ferite al punto da non riuscire più a reggersi; che gli altri rallentavano e che alcuni, nelle ultime file, abbandonavano la posizione, uscivano dalla battaglia ed evitavano i colpi; che i nemici, salendo di fronte dal terreno più basso, non davano tregua e premevano da entrambi i lati, e che la situazione era critica, e che non c\'era alcuna riserva da poter mandare avanti. **2.** Allora, tolto lo scudo a un soldato delle ultime file, poiché egli stesso era arrivato là senza, avanzò nella prima linea e, chiamando i centurioni per nome ed esortando gli altri soldati, ordinò di portare avanti le insegne e di allargare i manipoli, perché potessero usare più agevolmente le spade. **3.** Il suo arrivo infuse speranza ai soldati e ne risollevò l\'animo, e poiché ciascuno per parte sua desiderava dare il meglio sotto gli occhi del comandante, anche nella propria estrema rovina, l\'assalto dei nemici fu un poco rallentato.',
  analysis: 'Section 1 is one sentence of about a hundred and thirty words, and it works by suspension. Seven separate disasters arrive as accusative-and-infinitive clauses, stacked one on another, and the verb that governs every one of them - *vidit* - does not appear until they are all in place. The reader is made to hold the whole battlefield in mind unresolved, which is exactly the state Caesar is describing.\n\nThen, the instant he acts, the syntax changes completely. *Processit... iussit*: short main verbs, active, indicative. The style does the narrative work; you can feel the sentence stop being paralysed.\n\nPublius Sextius Baculus is one of the very few ordinary Romans Caesar names, and he names him three times across the corpus, always half dead and always still fighting. There is affection in that, of the sort Caesar rarely lets show.\n\n*Manipulos laxare*, "open out the maniples", is the tactical detail that makes the anecdote credible: the Twelfth was so compressed it could not swing a sword, which is what section 1 said at the very start. And note that the man who seizes a shield and walks into the front rank is called *Caesar*, in the third person, throughout. He never says "I". That distance is the trick the whole *Corpus Caesarianum* runs on: it lets the author praise himself in the register of a report.\n\n**[uni]** is in square brackets as an editorial supplement, printed here as the source prints it.',
  analysisIt: 'Il paragrafo 1 è un\'unica frase di circa centotrenta parole, e funziona per sospensione. Sette disastri distinti arrivano come proposizioni infinitive, accatastate una sull\'altra, e il verbo che le regge tutte - *vidit* - non compare finché non sono tutte al loro posto. Il lettore è costretto a tenere in mente l\'intero campo di battaglia senza scioglimento, che è esattamente la situazione descritta.\n\nPoi, nell\'istante in cui Cesare agisce, la sintassi cambia del tutto. *Processit... iussit*: verbi principali brevi, attivi, all\'indicativo. È lo stile a fare il lavoro narrativo: si sente la frase smettere di essere paralizzata.\n\nPublio Sestio Baculo è uno dei pochissimi Romani comuni che Cesare nomini, e lo nomina tre volte in tutto il corpus, sempre mezzo morto e sempre ancora in piedi a combattere. C\'è dell\'affetto, in questo, del genere che Cesare raramente lascia trasparire.\n\n*Manipulos laxare*, "allargare i manipoli", è il dettaglio tattico che rende credibile l\'aneddoto: la Dodicesima era così compressa da non poter menare un colpo di spada, che è proprio ciò che il paragrafo 1 diceva fin dall\'inizio. E si noti che l\'uomo che afferra uno scudo e va in prima fila si chiama *Cesare*, in terza persona, per tutto il brano. Non dice mai "io". Quella distanza è il trucco su cui gira l\'intero *Corpus Caesarianum*: permette all\'autore di elogiare se stesso nel registro di un rapporto.\n\n**[uni]** sta fra parentesi quadre come integrazione editoriale, ed è stampato qui come lo stampa la fonte.'
},

{
  work: 'bg-ii', key: 'bg.2.27', prefix: '[27] ',
  citation: '(De Bello Gallico II.27-28)',
  title: 'They fought from a mound made of their own dead',
  titleIt: 'Combatterono da un cumulo fatto dei loro stessi morti',
  description: 'The battle against the Nervii turns, and Caesar pays the enemy the finest compliment in the whole work. Then he records what was left of them: three senators out of six hundred, five hundred fighting men out of sixty thousand - and spares them.',
  descriptionIt: 'La battaglia contro i Nervi si rovescia, e Cesare tributa al nemico l\'elogio più bello di tutta l\'opera. Poi registra ciò che ne restava: tre senatori su seicento, cinquecento uomini in armi su sessantamila. E li risparmia.',
  english: '> [27] **1.** At their arrival so great a change of affairs took place that our men, even those who had collapsed worn out with wounds, leaned on their shields and renewed the fight; the camp servants, seeing the enemy terrified, ran at armed men though unarmed themselves; **2.** and the cavalry, to wipe out the disgrace of their flight by valour, pushed themselves ahead of the legionaries at every point of the battle. **3.** But the enemy, even in the last hope of safety, showed such valour that, when the front rank of them had fallen, the next stood on the bodies of the fallen and fought from them; **4.** and when these had been struck down and the corpses heaped up, those who were left threw weapons at us as if from a mound and sent back the javelins they had caught; **5.** so that it had to be judged not for nothing that men of such valour had dared to cross a very wide river, climb very high banks and take on very unfavourable ground - things which greatness of spirit had turned from the hardest into the easy.\n>\n> [28] **1.** With this battle fought and the people and the very name of the Nervii brought almost to extermination, their elders, whom we said had been driven together with the children and the women into the tidal creeks and the marshes, when this battle had been reported to them, and since they judged that nothing stood in the victors\' way and nothing was safe for the vanquished, **2.** by the agreement of all who survived sent envoys to Caesar and surrendered to him; and in recounting the disaster of their state they said that from six hundred senators they had been reduced to three, and from sixty thousand men who could bear arms to barely five hundred. **3.** These men Caesar, so that he might be seen to have used mercy towards the wretched and the suppliant, preserved with the greatest care, and ordered them to keep their own territory and towns, and commanded their neighbours to restrain themselves and their own people from injury and harm.',
  italian: '> [27] **1.** Al loro arrivo avvenne un mutamento di situazione così grande che i nostri, perfino quelli che erano crollati stremati dalle ferite, appoggiandosi agli scudi ripresero il combattimento; gli attendenti, vedendo i nemici atterriti, si lanciavano contro uomini armati pur essendo essi stessi disarmati; **2.** e i cavalieri, per cancellare con il valore la vergogna della fuga, si spingevano davanti ai legionari in ogni punto della battaglia. **3.** Ma i nemici, anche nell\'estrema speranza di salvezza, mostrarono un valore tale che, caduti i primi di loro, i successivi salivano sui corpi dei caduti e da lì combattevano; **4.** e abbattuti anche questi e ammucchiati i cadaveri, quelli che restavano lanciavano contro di noi i proiettili come da un cumulo e rimandavano indietro i giavellotti intercettati; **5.** al punto che si doveva giudicare non invano che uomini di tale valore avessero osato attraversare un fiume larghissimo, salire rive altissime, affrontare un terreno sfavorevolissimo: cose che la grandezza d\'animo aveva reso facili da difficilissime che erano.\n>\n> [28] **1.** Combattuta questa battaglia e ridotti quasi allo sterminio il popolo e il nome stesso dei Nervi, i loro anziani, che abbiamo detto essere stati sospinti insieme ai fanciulli e alle donne negli estuari e nelle paludi, quando fu loro riferita questa battaglia, e poiché ritenevano che nulla ostacolasse i vincitori e nulla fosse sicuro per i vinti, **2.** con il consenso di tutti i superstiti mandarono ambasciatori a Cesare e si arresero a lui; e nel ricordare la rovina della loro nazione dissero di essere stati ridotti da seicento senatori a tre, e da sessantamila uomini in grado di portare le armi a poco meno di cinquecento. **3.** Costoro Cesare, perché apparisse aver usato misericordia verso gli infelici e i supplici, li conservò con la massima cura e ordinò loro di tenere il proprio territorio e le proprie città, e comandò ai confinanti di trattenere se stessi e i propri uomini da ogni offesa e danno.',
  analysis: 'This is the one place where Caesar lets the style swell, and he does it for the enemy. Four superlatives fall inside a single clause - *latissimum flumen, altissimas ripas, iniquissimum locum*, answered by *ex difficillimis* - in an author who normally will not spend an adjective. The image of men fighting from a rampart built out of their own dead is the most extraordinary thing in the seven books, and Caesar does not soften it with a word of horror.\n\nBe clear about who benefits. The braver the Nervii, the greater the victory over them; praising a defeated enemy is the cheapest and most effective form of self-praise there is, and Caesar knew it. But the praise also reads as sincere, and both things are true at once - which is roughly the reading experience of the whole work.\n\nThe numbers in section 28.2 should be set beside the Helvetian tablets of *De Bello Gallico* I.29. There the arithmetic is a Roman document, dispassionate and administrative; here it is put in the mouths of the survivors themselves, *in commemoranda civitatis calamitate*, and so cannot be blamed on the author. Same technique, different disguise.\n\nAnd then the most revealing three words in the batch: *ut... videretur*, "so that he might be seen to". Caesar does not say he pitied them. He says he preserved them so that his use of mercy might be visible. *Clementia* here is a policy with an audience in Rome - the same quality that Cato would call an insult to free men, and that Caesar would build a political brand on. Read the chapters that follow and the point sharpens: the Aduatuci, who tried the same surrender a few pages later and broke faith, were sold entire, and Caesar records the buyers\' receipt for 53,000 heads. The juxtaposition is his own.',
  analysisIt: 'È l\'unico punto in cui Cesare lascia gonfiare lo stile, e lo fa per il nemico. Quattro superlativi cadono dentro un\'unica proposizione - *latissimum flumen, altissimas ripas, iniquissimum locum*, con la risposta di *ex difficillimis* - in un autore che di norma non spende un aggettivo. L\'immagine di uomini che combattono da un terrapieno costruito con i propri morti è la cosa più straordinaria dei sette libri, e Cesare non la addolcisce con una parola di orrore.\n\nSia chiaro a chi giova. Più i Nervi sono valorosi, più grande è la vittoria su di loro: elogiare un nemico sconfitto è la forma più economica ed efficace di autoelogio che esista, e Cesare lo sapeva. Ma l\'elogio suona anche sincero, e le due cose sono vere insieme, che è più o meno l\'esperienza di lettura di tutta l\'opera.\n\nI numeri del paragrafo 28.2 vanno messi accanto alle tavolette elvetiche del *De Bello Gallico* I.29. Là l\'aritmetica è un documento romano, distaccato e amministrativo; qui è messa in bocca ai superstiti stessi, *in commemoranda civitatis calamitate*, e dunque non può essere addebitata all\'autore. Stessa tecnica, travestimento diverso.\n\nE poi le tre parole più rivelatrici del gruppo: *ut... videretur*, "perché apparisse". Cesare non dice di aver avuto pietà. Dice di averli conservati perché il suo uso della misericordia fosse visibile. La *clementia* è qui una politica con un pubblico a Roma: la stessa qualità che Catone avrebbe chiamato un insulto agli uomini liberi, e su cui Cesare avrebbe costruito il proprio marchio politico. Si leggano i capitoli successivi e il punto si affila: gli Atuatuci, che tentarono la stessa resa poche pagine dopo e vennero meno alla parola, furono venduti in blocco, e Cesare registra la ricevuta degli acquirenti per 53.000 teste. L\'accostamento è suo.'
}

];
